import { PolicyPage, type PolicySection } from '@/components/sections/PolicyPage';

const sections: PolicySection[] = [
  {
    title: '1. About this Policy',
    blocks: [
      `This Refund and Cancellation Policy explains when an ArvoSim Order may be cancelled and when a refund, replacement, Wallet adjustment or other remedy may be available.`,
      `This Policy applies to:`,
      [
        `eSIM Plans purchased using Wallet Balance;`,
        `Wallet top-ups made using an accepted payment card;`,
        `Orders that are delayed, unavailable or not delivered;`,
        `faulty, invalid or incorrectly supplied eSIMs;`,
        `duplicate or unauthorised transactions; and`,
        `unused Wallet Balance when an Account is permanently closed.`,
      ],
      `This Policy forms part of the ArvoSim Terms and Conditions and should be read together with our:`,
      [
        `Terms and Conditions;`,
        `eSIM Delivery and Activation Policy;`,
        `Payment and Wallet Policy;`,
        `Privacy Policy; and`,
        `Complaints and Dispute Resolution Policy.`,
      ],
      `ArvoSim is operated by ARVO LINE LTD, company number 17221404, Dept 6800, 196 High Road, Wood Green, London, United Kingdom, N22 8HH. Email: info@arvosim.com. Website: arvosim.com.`,
      `In this Policy, "ArvoSim", "we", "us" and "our" refer to ARVO LINE LTD.`,
    ],
  },
  {
    title: '2. Definitions',
    blocks: [
      `For the purposes of this Policy:`,
      [
        `Account means a registered ArvoSim user account.`,
        `Cash-Funded Balance means Wallet Balance created through a successful payment made by the user, excluding promotional or complimentary credit.`,
        `eSIM means an electronic SIM profile supplied digitally through a QR code or equivalent installation information.`,
        `eSIM Plan or Plan means a prepaid mobile data package purchased through ArvoSim.`,
        `Order means a request to purchase an eSIM Plan using Wallet Balance.`,
        `Promotional Credit means Wallet credit provided without a corresponding payment, including bonuses, referral rewards, promotional balances and goodwill credits.`,
        `Used eSIM means an eSIM that network or provider records show has connected to a Supported Network and consumed any amount of mobile data.`,
        `Wallet Balance means prepaid Account credit that may be used to purchase eligible eSIM Plans through ArvoSim.`,
      ],
    ],
  },
  {
    title: '3. Wallet-Only Purchase Model',
    blocks: [
      `ArvoSim operates a Wallet-only purchasing model.`,
      `This means that:`,
      [
        `the user first adds funds to their Wallet Balance;`,
        `the user then purchases an eSIM Plan using that Wallet Balance; and`,
        `the eSIM Plan is not charged directly to the payment card.`,
      ],
      `As a result, different refund rules apply to:`,
      [
        `the cancellation or refund of an eSIM Order;`,
        `the reversal of a Wallet top-up; and`,
        `the return of unused Wallet Balance when an Account is permanently closed.`,
      ],
      `Unless this Policy expressly states otherwise, an approved refund for an eSIM Plan will be returned to the Wallet Balance from which the Plan was purchased.`,
    ],
  },
  {
    title: '4. Cancellation Before eSIM Delivery',
    blocks: [
      `You may request cancellation of an Order before the eSIM QR code or equivalent activation information has been delivered.`,
      `To request cancellation, email info@arvosim.com and include:`,
      [
        `the email address associated with your Account;`,
        `the Order reference;`,
        `the destination and Plan;`,
        `the date of the Order; and`,
        `a clear request to cancel.`,
      ],
      `ArvoSim Orders are processed manually. We therefore cannot guarantee that a cancellation request will be reviewed before delivery if fulfilment is already underway.`,
      `If the Order has not yet been accepted or fulfilled, the full Plan price will be restored to your Wallet Balance without an administrative deduction.`,
    ],
  },
  {
    title: '5. Cancellation After Digital Delivery',
    blocks: [
      `An eSIM is digital content supplied without a physical medium.`,
      `Where applicable, the user may be asked during the ordering process to:`,
      [
        `expressly request or consent to delivery before the end of any statutory cancellation period; and`,
        `acknowledge that the statutory right to cancel may be lost when digital supply begins.`,
      ],
      `Digital supply begins when the QR code or equivalent activation information is delivered to the email address associated with the Account.`,
      `The loss of a statutory cancellation right following valid consent does not remove:`,
      [
        `ArvoSim's voluntary 30-day refund right for unused eSIM Plans;`,
        `rights relating to faulty, unavailable or misdescribed digital content; or`,
        `any other rights that cannot lawfully be excluded.`,
      ],
    ],
  },
  {
    title: '6. Voluntary 30-Day Refund for an Unused eSIM',
    blocks: [
      `ArvoSim offers a full refund for an unused eSIM Plan where:`,
      [
        `the refund request is submitted within 30 calendar days of the Order date;`,
        `the eSIM has not connected to a Supported Network and consumed data;`,
        `the relevant Order can be identified;`,
        `the user provides any reasonable information required to verify non-use; and`,
        `the request is not fraudulent, abusive or part of repeated misuse of the refund process.`,
      ],
      `The full Plan price will be restored to the Wallet Balance without an administrative or cancellation fee.`,
      `This voluntary refund may be available even if:`,
      [
        `the QR code has already been delivered;`,
        `the eSIM has been installed but has not connected or consumed data;`,
        `the user purchased the wrong destination or Plan;`,
        `the user's travel plans changed; or`,
        `the user no longer requires the Plan.`,
      ],
      `Installation by itself does not necessarily mean that an eSIM has been used.`,
    ],
  },
  {
    title: '7. When an eSIM Is Considered Used',
    blocks: [
      `An eSIM is considered used when reliable network or provider records show that it has:`,
      [
        `connected to a Supported Network; and`,
        `consumed any amount of mobile data.`,
      ],
      `Network and technical-provider records will normally be the primary evidence of activation and usage. We may also consider:`,
      [
        `Account records;`,
        `device screenshots;`,
        `connection logs;`,
        `support correspondence;`,
        `the time of activation;`,
        `the quantity of data consumed; and`,
        `evidence of a technical reporting error.`,
      ],
      `If there is a genuine dispute about whether an eSIM was used, we will review the available information reasonably and in good faith.`,
    ],
  },
  {
    title: '8. Refunds for Used eSIM Plans',
    blocks: [
      `A Used eSIM is not ordinarily eligible for a change-of-mind refund.`,
      `A refund, price reduction, replacement or other remedy may nevertheless be available where:`,
      [
        `the eSIM was faulty;`,
        `the Plan was materially different from its description;`,
        `the supplied coverage materially differed from the purchased destination;`,
        `the eSIM stopped functioning because of a fault attributable to ArvoSim or its providers;`,
        `the user received substantially less service than was purchased;`,
        `the same technical problem continued after reasonable troubleshooting or replacement; or`,
        `applicable law requires another remedy.`,
      ],
      `Where the user received part of the purchased benefit, a proportionate Wallet refund or price reduction may be offered.`,
      `Where the user received no meaningful benefit, a full refund may be appropriate.`,
    ],
  },
  {
    title: '9. Non-Delivery',
    blocks: [
      `If the QR code has not been received within a reasonable period after the Order was submitted, you should:`,
      [
        `check spam, junk and promotions folders;`,
        `confirm that the Account email address is correct;`,
        `search the mailbox for messages from ArvoSim; and`,
        `contact info@arvosim.com with the Order details.`,
      ],
      `We will investigate whether the Order was:`,
      [
        `successfully submitted;`,
        `accepted;`,
        `manually processed;`,
        `sent to the correct email address;`,
        `rejected or delayed by the email service;`,
        `affected by a technical failure; or`,
        `unavailable for fulfilment.`,
      ],
      `Depending on the circumstances, we may:`,
      [
        `complete the Order;`,
        `resend the delivery email;`,
        `provide the QR code to a verified replacement email address;`,
        `issue a replacement eSIM;`,
        `offer an equivalent Plan; or`,
        `restore the full Plan price to the Wallet Balance.`,
      ],
      `If the Order cannot be fulfilled, the full Plan price will be restored without an administrative deduction.`,
    ],
  },
  {
    title: '10. Delayed Delivery',
    blocks: [
      `The eSIM QR code is normally delivered within several hours after a valid Order is submitted, but this is an indicative processing period rather than a guaranteed deadline.`,
      `If delivery is materially delayed, you may request cancellation while the Order remains unfulfilled.`,
      `Where:`,
      [
        `a specific delivery deadline was expressly agreed;`,
        `delivery by that deadline was essential and communicated to us; or`,
        `the delay defeats the principal purpose of the Order,`,
      ],
      `we will assess the request promptly and provide any remedy required by applicable law.`,
      `Users should submit Orders sufficiently in advance of the time when connectivity is required because Orders are manually processed.`,
    ],
  },
  {
    title: '11. Plan Unavailability',
    blocks: [
      `An eSIM Plan may become unavailable after an Order is submitted because of:`,
      [
        `a provider or network restriction;`,
        `a provisioning failure;`,
        `a change in destination coverage;`,
        `temporary capacity limitations;`,
        `a legal or sanctions restriction;`,
        `a technical or pricing error; or`,
        `circumstances outside our reasonable control.`,
      ],
      `If we cannot supply the selected Plan, we may offer:`,
      [
        `a materially equivalent Plan;`,
        `another Plan for the same destination;`,
        `restoration of the full Plan price to the Wallet Balance; or`,
        `another remedy required by applicable law.`,
      ],
      `We will not substitute a materially different Plan without your agreement.`,
      `You may reject a proposed replacement and request restoration of the full Plan price to your Wallet Balance.`,
    ],
  },
  {
    title: '12. Invalid or Faulty QR Code',
    blocks: [
      `You should contact us if the QR code:`,
      [
        `cannot be scanned;`,
        `is shown as invalid;`,
        `has already been used before you received it;`,
        `does not install the purchased eSIM profile;`,
        `produces an unexplained activation error; or`,
        `contains incorrect provisioning information.`,
      ],
      `Before approving a refund, we may reasonably attempt to:`,
      [
        `provide manual installation information;`,
        `resend the QR code;`,
        `correct the provisioning details;`,
        `issue a replacement QR code;`,
        `replace the eSIM; or`,
        `provide an equivalent Plan.`,
      ],
      `You should not repeatedly scan the QR code, delete a partially installed eSIM or attempt installation on several devices unless instructed to do so.`,
    ],
  },
  {
    title: '13. eSIM Installs but Does Not Connect',
    blocks: [
      `If the eSIM installs but does not connect, we may ask you to check:`,
      [
        `whether you are within the Plan's coverage area;`,
        `whether the eSIM line is enabled;`,
        `whether the ArvoSim eSIM is selected for mobile data;`,
        `whether data roaming is enabled where required;`,
        `whether automatic mobile-data switching is disabled;`,
        `whether the correct APN settings are entered;`,
        `whether a Supported Network is available;`,
        `whether the device is carrier-unlocked; and`,
        `whether restarting the device or toggling airplane mode resolves the issue.`,
      ],
      `We may require reasonable cooperation with troubleshooting before determining whether the eSIM is faulty.`,
      `Troubleshooting must be completed within a reasonable time and without causing significant inconvenience, taking account of:`,
      [
        `the user's travel dates;`,
        `the period for which the Plan was purchased;`,
        `the urgency of connectivity;`,
        `the duration of the problem; and`,
        `the practical availability of a replacement.`,
      ],
    ],
  },
  {
    title: '14. Repair, Replacement and Price Reduction',
    blocks: [
      `Where an eSIM does not materially conform to the contract, we may first provide an appropriate remedy by:`,
      [
        `correcting the configuration;`,
        `repairing or reprovisioning the eSIM;`,
        `resending activation information;`,
        `issuing a replacement eSIM; or`,
        `supplying a materially equivalent replacement Plan.`,
      ],
      `A repair or replacement will be provided without an additional charge where the fault is attributable to ArvoSim or its providers.`,
      `If repair or replacement:`,
      [
        `is impossible;`,
        `is disproportionate;`,
        `is not completed within a reasonable time; or`,
        `causes significant inconvenience,`,
      ],
      `you may be entitled to an appropriate price reduction.`,
      `The price reduction may be up to the full Plan price where the eSIM provided no meaningful benefit.`,
    ],
  },
  {
    title: '15. Incorrect Plan or Destination',
    blocks: [
      `If you purchase the wrong Plan or destination, you may request a full refund to the Wallet Balance under the voluntary 30-day refund right, provided that the eSIM remains unused.`,
      `If the eSIM has already connected and consumed data, a refund will not normally be available merely because:`,
      [
        `the wrong destination was selected;`,
        `the wrong data allowance was selected;`,
        `the user misunderstood the Plan validity period; or`,
        `the user later preferred a different Plan.`,
      ],
      `This does not affect remedies where the Plan description was inaccurate, unclear or materially misleading.`,
    ],
  },
  {
    title: '16. Device Incompatibility',
    blocks: [
      `Users are responsible for checking before purchase that their device:`,
      [
        `supports eSIM technology;`,
        `is not locked to another network;`,
        `supports the relevant network bands;`,
        `permits installation of another eSIM;`,
        `has compatible software; and`,
        `can use data roaming where required.`,
      ],
      `An unused eSIM may still qualify for the voluntary 30-day refund where the device proves incompatible.`,
      `Once the eSIM has connected and consumed data, incompatibility with another device, a later device change or a preferred device configuration will not normally create a refund right.`,
      `Nothing in this section limits rights where ArvoSim provided materially incorrect compatibility information that the user reasonably relied upon.`,
    ],
  },
  {
    title: '17. Deleted, Shared or Transferred eSIMs',
    blocks: [
      `You should contact support before deleting an eSIM that is not functioning correctly.`,
      `A replacement or refund may be refused where the problem was caused by:`,
      [
        `deleting a functioning eSIM;`,
        `attempting to transfer it to another device;`,
        `installing it on the wrong device;`,
        `sharing or publishing the QR code;`,
        `allowing another person to use the eSIM; or`,
        `compromising the activation information.`,
      ],
      `However, an unused eSIM may remain eligible for the voluntary 30-day refund where provider records confirm that no data was consumed and there is no evidence of fraud or abuse.`,
    ],
  },
  {
    title: '18. Coverage and Speed Complaints',
    blocks: [
      `Mobile coverage and performance may vary because of:`,
      [
        `local network availability;`,
        `network congestion;`,
        `geographic conditions;`,
        `buildings and physical obstructions;`,
        `device capabilities;`,
        `supported network frequencies;`,
        `temporary maintenance;`,
        `weather or infrastructure incidents;`,
        `local restrictions; and`,
        `the availability of 4G, LTE or 5G.`,
      ],
      `A refund will not normally be provided solely because:`,
      [
        `the connection was slower than expected;`,
        `5G was unavailable but another supported data connection worked;`,
        `coverage was weaker in a particular building or location;`,
        `a specific local network was unavailable while another Supported Network worked; or`,
        `temporary congestion affected performance.`,
      ],
      `A refund or price reduction may be considered where the Plan was materially unusable throughout a substantial part of the covered destination and the problem was attributable to the supplied service rather than local or device-specific conditions.`,
    ],
  },
  {
    title: '19. Data Consumption',
    blocks: [
      `Refunds are not normally available for data consumed through:`,
      [
        `automatic software updates;`,
        `cloud backups;`,
        `video or audio streaming;`,
        `application downloads;`,
        `hotspot or tethering use;`,
        `background applications;`,
        `operating-system services;`,
        `incorrect device settings; or`,
        `unauthorised access caused by the user's failure to secure the device.`,
      ],
      `Users are responsible for monitoring usage and controlling device settings.`,
      `We will investigate credible evidence that usage records are technically incorrect or that data was consumed because of a service fault.`,
    ],
  },
  {
    title: '20. Duplicate Orders',
    blocks: [
      `If you accidentally purchase the same or a substantially identical Plan more than once, contact us promptly.`,
      `Where the duplicate eSIM remains unused, we will normally restore the duplicate Plan price to the Wallet Balance.`,
      `If both eSIMs have been activated and used, we will assess the request based on:`,
      [
        `the amount of data consumed;`,
        `the circumstances of the duplicate purchase;`,
        `whether the Website or Service caused the duplication; and`,
        `applicable consumer rights.`,
      ],
    ],
  },
  {
    title: '21. Wallet Top-Ups',
    blocks: [
      `Wallet top-ups are not ordinarily refundable or withdrawable while an Account remains active.`,
      `Exceptions may apply where:`,
      [
        `the payment was duplicated;`,
        `the wrong amount was charged because of a technical error;`,
        `the payment was unauthorised;`,
        `the Wallet credit was not provided;`,
        `the payment was accepted but the Wallet service cannot be provided;`,
        `applicable law requires a refund; or`,
        `the Account is permanently closed in accordance with Section 24.`,
      ],
      `The non-refundable nature of ordinary Wallet top-ups does not allow ArvoSim to retain money resulting from an established payment error, unauthorised transaction or legal entitlement to reimbursement.`,
    ],
  },
  {
    title: '22. Accidental Wallet Top-Ups',
    blocks: [
      `If you make an accidental Wallet top-up, contact us promptly before spending any part of the credited balance.`,
      `We may consider a reversal where:`,
      [
        `the Wallet credit remains completely unused;`,
        `the request is made promptly;`,
        `the original payment can be identified and reversed;`,
        `no eSIM Order has been placed using the credit;`,
        `no fraud or abuse is suspected; and`,
        `reversal is operationally and legally possible.`,
      ],
      `Any such reversal is discretionary unless required by applicable law.`,
      `Once the Wallet credit has been used, the ordinary eSIM refund rules will apply to the relevant Order.`,
    ],
  },
  {
    title: '23. Unauthorised Payments',
    blocks: [
      `If you believe that a Wallet top-up was made without your permission, contact:`,
      [
        `your card issuer or payment provider; and`,
        `ArvoSim at info@arvosim.com.`,
      ],
      `You should provide:`,
      [
        `the Account email address;`,
        `the transaction date;`,
        `the amount;`,
        `the payment reference, if available; and`,
        `a description of why the transaction is unauthorised.`,
      ],
      `Do not send full card details, passwords or authentication codes by email.`,
      `We may temporarily restrict the Account while investigating the transaction.`,
      `If the payment is confirmed as unauthorised, we may reverse the corresponding Wallet credit and process any required refund through the relevant payment channel.`,
    ],
  },
  {
    title: '24. Refund of Wallet Balance on Account Closure',
    blocks: [
      `An Account cannot currently be closed through a self-service function.`,
      `To request permanent Account closure, email info@arvosim.com from the email address associated with the Account.`,
      `Before closing the Account, we may need to:`,
      [
        `verify your identity and Account ownership;`,
        `complete or cancel pending Orders;`,
        `resolve refunds or payment disputes;`,
        `investigate suspected unauthorised activity;`,
        `identify the source of Wallet funds; and`,
        `deduct any amount validly owed because of a reversed payment or chargeback.`,
      ],
      `Following final Account closure, the verified unused Cash-Funded Balance will be returned without an administrative deduction.`,
      `The refund will normally be made to the original payment method where reasonably possible.`,
      `Where:`,
      [
        `several payment methods were used;`,
        `the original payment method is no longer available;`,
        `the original payment method cannot receive the refund; or`,
        `technical restrictions prevent the original route,`,
      ],
      `we may request reasonable alternative payment information or agree another refund method with the user.`,
    ],
  },
  {
    title: '25. Promotional Credit',
    blocks: [
      `Promotional Credit:`,
      [
        `does not represent a payment made by the user;`,
        `is not redeemable for cash;`,
        `is not included in the cash refund due on Account closure;`,
        `may be subject to separate promotional conditions; and`,
        `may be removed if obtained through fraud or abuse.`,
      ],
      `If an eSIM was purchased partly with Cash-Funded Balance and partly with Promotional Credit, any approved refund will normally be returned in the same proportions:`,
      [
        `the cash-funded portion as Cash-Funded Balance; and`,
        `the promotional portion as Promotional Credit.`,
      ],
      `Promotional Credit may be restored only while the relevant promotion remains valid, unless otherwise required by its terms.`,
    ],
  },
  {
    title: '26. How to Request a Refund',
    blocks: [
      `Refund requests must be sent to: info@arvosim.com`,
      `The request should include:`,
      [
        `the email address associated with the Account;`,
        `the Order reference;`,
        `the destination and Plan;`,
        `the date of purchase;`,
        `the reason for the request;`,
        `the device model, where relevant;`,
        `screenshots of any error;`,
        `a summary of troubleshooting already completed; and`,
        `the remedy requested.`,
      ],
      `Do not include:`,
      [
        `full payment-card numbers;`,
        `card security codes;`,
        `Account passwords;`,
        `authentication codes; or`,
        `unnecessary sensitive personal information.`,
      ],
      `Failure to provide relevant information may delay the investigation but will not remove rights that apply under law.`,
    ],
  },
  {
    title: '27. Refund Review',
    blocks: [
      `We will review:`,
      [
        `the Order history;`,
        `delivery records;`,
        `activation and usage records;`,
        `Wallet transactions;`,
        `support correspondence;`,
        `technical-provider information;`,
        `evidence supplied by the user; and`,
        `any suspected fraud or abuse.`,
      ],
      `We may ask for additional reasonable information where necessary.`,
      `We will not require technical evidence that would be impossible or unreasonably difficult for an ordinary consumer to obtain.`,
    ],
  },
  {
    title: '28. Refund Method',
    blocks: [
      `The refund method depends on the type of transaction.`,
      `28.1 eSIM Plan refund — Because eSIM Plans are purchased using Wallet Balance, an approved voluntary eSIM refund will normally be restored to the Wallet Balance.`,
      `28.2 Wallet top-up refund — Where a Wallet top-up qualifies for refund, the amount will normally be returned to the original payment method.`,
      `28.3 Account closure — Verified unused Cash-Funded Balance will normally be returned to the original payment method or another agreed method where the original route is unavailable.`,
      `28.4 Mandatory monetary refunds — Where applicable law entitles a Consumer to a monetary refund rather than Account credit, we will provide the refund using the method required by law or another method expressly agreed with the Consumer.`,
      `We will not impose an administrative fee on an approved full refund.`,
    ],
  },
  {
    title: '29. Processing Times',
    blocks: [
      `We will process approved refunds without undue delay.`,
      `Wallet Balance adjustments will normally be completed within five business days after approval.`,
      `Where a payment-card refund is required:`,
      [
        `ArvoSim will normally initiate it within five business days after approval;`,
        `statutory refunds will be initiated within any shorter or mandatory legal period that applies; and`,
        `the card issuer or payment provider may require additional time to display the refund.`,
      ],
      `Card refunds commonly appear within 5–10 business days after processing, although the precise timing is controlled by the card issuer or payment provider.`,
    ],
  },
  {
    title: '30. Currency Conversion',
    blocks: [
      `Wallet Balance and eSIM Plan transactions are maintained in GBP.`,
      `Where a payment-card refund is made, we will refund the applicable GBP amount.`,
      `If the original card payment involved currency conversion:`,
      [
        `the card issuer may use a different exchange rate when processing the refund;`,
        `foreign transaction charges may not be reversed;`,
        `the amount shown in another currency may differ from the original converted amount; and`,
        `ArvoSim does not retain or control the card issuer's exchange-rate difference.`,
      ],
      `This does not affect the requirement to refund the correct GBP amount.`,
    ],
  },
  {
    title: '31. Chargebacks and Payment Disputes',
    blocks: [
      `If you recognise a transaction but believe that an Order, Wallet credit or refund was handled incorrectly, please contact info@arvosim.com before initiating a chargeback.`,
      `This allows us to:`,
      [
        `investigate the issue;`,
        `correct an error;`,
        `complete a pending refund;`,
        `provide delivery evidence; and`,
        `avoid unnecessary restrictions on the Account.`,
      ],
      `Nothing in this Policy prevents you from exercising rights available through your card issuer, payment provider or applicable law.`,
      `Where a chargeback is initiated, we may temporarily suspend the corresponding Wallet Balance or Account while the matter is investigated.`,
      `If a payment is reversed after its Wallet credit has been spent, we may deduct the reversed amount from the Wallet Balance or require repayment of the resulting negative balance.`,
    ],
  },
  {
    title: '32. Refund Abuse and Fraud',
    blocks: [
      `We may refuse a voluntary refund, suspend an Account or investigate further where there is reasonable evidence of:`,
      [
        `repeated purchases followed by refund requests;`,
        `attempts to use an eSIM and then claim it was unused;`,
        `manipulation of activation or usage records;`,
        `duplicate claims through ArvoSim and a card issuer;`,
        `use of stolen or unauthorised payment information;`,
        `creation of multiple Accounts to obtain repeated refunds;`,
        `abuse of promotional credit;`,
        `false screenshots or misleading information; or`,
        `attempts to retain both a refund and the purchased benefit.`,
      ],
      `We will not refuse a valid statutory remedy merely because the user previously requested another legitimate refund.`,
    ],
  },
  {
    title: '33. Business Users',
    blocks: [
      `The voluntary refund rights stated in this Policy apply to Business Users unless a separate written business agreement provides otherwise.`,
      `Statutory consumer protections described in this Policy apply only where the user qualifies as a Consumer.`,
      `Nothing in this Policy limits rights or remedies that cannot legally be excluded from a Business User.`,
    ],
  },
  {
    title: '34. Consumer Rights',
    blocks: [
      `This Policy provides contractual and voluntary rights in addition to any mandatory rights available under applicable consumer law.`,
      `Nothing in this Policy excludes or limits rights relating to digital content that is:`,
      [
        `not of satisfactory quality;`,
        `not fit for a purpose made known to us;`,
        `not as described;`,
        `supplied without the legal right to do so;`,
        `not repaired or replaced within a reasonable time;`,
        `not repaired or replaced without significant inconvenience; or`,
        `otherwise non-compliant with mandatory law.`,
      ],
      `Where mandatory law provides a more favourable remedy than this Policy, the mandatory legal right will apply.`,
    ],
  },
  {
    title: '35. Complaints',
    blocks: [
      `If you disagree with a refund decision, you may request reconsideration by replying to the decision or emailing info@arvosim.com.`,
      `Please explain:`,
      [
        `why you disagree;`,
        `what information may have been overlooked;`,
        `the remedy you consider appropriate; and`,
        `any new evidence supporting the request.`,
      ],
      `The matter will be reviewed in accordance with the Complaints and Dispute Resolution Policy.`,
      `Nothing in this section prevents a Consumer from using any court, regulator, payment-provider process or alternative dispute mechanism available under applicable law.`,
    ],
  },
  {
    title: '36. Changes to this Policy',
    blocks: [
      `We may update this Policy to reflect changes to:`,
      [
        `the Service;`,
        `Wallet functionality;`,
        `eSIM delivery;`,
        `payment-provider requirements;`,
        `refund processes;`,
        `applicable law; or`,
        `our business operations.`,
      ],
      `The updated Policy will be published on arvosim.com with a revised "Last updated" date.`,
      `Changes will not retrospectively reduce rights relating to an Order already accepted.`,
    ],
  },
  {
    title: '37. Contact Information',
    blocks: [
      `Questions, cancellation requests and refund claims may be directed to ARVO LINE LTD, company number 17221404, Dept 6800, 196 High Road, Wood Green, London, United Kingdom, N22 8HH.`,
      `Email: info@arvosim.com. Website: arvosim.com.`,
    ],
  },
];

export default function RefundPage() {
  return (
    <PolicyPage
      title="Refund and Cancellation Policy"
      lastUpdated="31 July 2026"
      intro="This Refund and Cancellation Policy explains when an ArvoSim Order may be cancelled and when a refund, replacement, Wallet adjustment or other remedy may be available."
      sections={sections}
    />
  );
}
