import { PolicyPage, type PolicySection } from '@/components/sections/PolicyPage';

const sections: PolicySection[] = [
  {
    title: '1. About this Policy',
    blocks: [
      `This Complaints and Dispute Resolution Policy explains how you may raise a complaint concerning ArvoSim and how we will review, investigate and respond to it.`,
      `It applies to complaints concerning:`,
      [
        `an ArvoSim Account;`,
        `Wallet Top-Ups or Wallet Balance;`,
        `payment processing;`,
        `an eSIM Order;`,
        `delivery of an eSIM QR code;`,
        `installation or activation;`,
        `network connectivity;`,
        `data usage;`,
        `cancellation or refund decisions;`,
        `Account restrictions or closure;`,
        `privacy and personal data;`,
        `Website functionality;`,
        `customer support; or`,
        `another aspect of the ArvoSim Service.`,
      ],
      `Our aim is to resolve complaints fairly, promptly and proportionately before they develop into formal disputes.`,
      `This Policy forms part of the ArvoSim Terms and Conditions and should be read together with our:`,
      [
        `Terms and Conditions;`,
        `eSIM Delivery and Activation Policy;`,
        `Refund and Cancellation Policy;`,
        `Payment and Wallet Policy;`,
        `Privacy Policy;`,
        `Cookie Policy; and`,
        `Acceptable Use Policy.`,
      ],
      `ArvoSim is operated by ARVO LINE LTD, company number 17221404, Dept 6800, 196 High Road, Wood Green, London, United Kingdom, N22 8HH. Email: info@arvosim.com. Website: arvosim.com.`,
      `In this Policy, "ArvoSim", "we", "us" and "our" refer to ARVO LINE LTD.`,
    ],
  },
  {
    title: '2. What Is a Complaint?',
    blocks: [
      `A complaint is an expression of dissatisfaction about:`,
      [
        `the Service provided by ArvoSim;`,
        `a failure to provide an expected service;`,
        `an action or decision taken by ArvoSim;`,
        `the conduct of our customer support;`,
        `the handling of an Order, payment or refund;`,
        `the use of personal data; or`,
        `another matter for which you reasonably expect an explanation, correction or remedy.`,
      ],
      `You do not need to use the word "complaint" for us to treat your message as one.`,
      `A request for ordinary technical assistance may initially be handled as a support request. If you express dissatisfaction with the handling, outcome or underlying service, it may be registered as a complaint.`,
    ],
  },
  {
    title: '3. Who May Submit a Complaint?',
    blocks: [
      `A complaint may be submitted by:`,
      [
        `the Account holder;`,
        `a person who completed or attempted a Wallet Top-Up;`,
        `a purchaser or intended user of an eSIM Plan;`,
        `a person whose personal data is processed by ArvoSim;`,
        `an authorised representative; or`,
        `another person directly affected by the matter.`,
      ],
      `Where a representative acts for another person, we may request reasonable evidence of:`,
      [
        `the representative's identity;`,
        `the complainant's identity; and`,
        `the representative's authority to act.`,
      ],
      `We will not disclose confidential Account, payment or personal information to an unauthorised person.`,
    ],
  },
  {
    title: '4. No Charge for Making a Complaint',
    blocks: [
      `ArvoSim does not charge a fee for submitting or investigating an ordinary complaint.`,
      `You will not lose a contractual or statutory right merely because you made a complaint.`,
      `We will not penalise a user for making a genuine complaint, requesting a refund, exercising a data protection right or disputing a transaction in good faith.`,
    ],
  },
  {
    title: '5. How to Submit a Complaint',
    blocks: [
      `Complaints should be submitted by email to: info@arvosim.com`,
      `Please use a clear subject line, such as: Complaint – Order [reference] or: Privacy Complaint – ArvoSim Account`,
      `Where possible, send the complaint from the email address associated with your Account.`,
      `Written complaints help us maintain an accurate record of:`,
      [
        `the issue raised;`,
        `supporting evidence;`,
        `communication dates;`,
        `investigation steps; and`,
        `the resolution offered.`,
      ],
    ],
  },
  {
    title: '6. Information to Include',
    blocks: [
      `To help us investigate efficiently, your complaint should include, where relevant:`,
      [
        `your full name;`,
        `the email address associated with your Account;`,
        `the Order reference;`,
        `the Wallet or payment reference;`,
        `the destination and eSIM Plan;`,
        `the date of the relevant transaction or event;`,
        `your device manufacturer and model;`,
        `your operating-system version;`,
        `a clear description of what happened;`,
        `relevant screenshots or error messages;`,
        `troubleshooting already completed;`,
        `previous correspondence;`,
        `the effect the problem had on you; and`,
        `the outcome or remedy you are seeking.`,
      ],
      `You should not send:`,
      [
        `your full card number;`,
        `your card security code;`,
        `an Account password;`,
        `a banking password;`,
        `a one-time authentication code; or`,
        `unnecessary sensitive personal information.`,
      ],
      `Failure to provide all requested information will not automatically invalidate a complaint, but it may delay our investigation.`,
    ],
  },
  {
    title: '7. Accessibility and Reasonable Assistance',
    blocks: [
      `We will take reasonable steps to make the complaint process accessible.`,
      `Where a person has difficulty submitting a complaint by ordinary email because of a disability, language barrier or another genuine accessibility need, they may contact us and request reasonable assistance or an alternative format.`,
      `We may also accept a complaint submitted by an authorised representative where appropriate.`,
    ],
  },
  {
    title: '8. Urgent eSIM and Travel Complaints',
    blocks: [
      `Complaints involving an immediate connectivity problem during travel should be clearly marked: URGENT eSIM SUPPORT`,
      `Examples include:`,
      [
        `a QR code that cannot be installed shortly before travel;`,
        `an eSIM that fails to connect at the destination;`,
        `a materially delayed Order required for imminent travel;`,
        `an invalid eSIM profile;`,
        `an incorrect destination Plan; or`,
        `an eSIM that unexpectedly stops working.`,
      ],
      `We will prioritise urgent technical issues where reasonably possible.`,
      `An urgent support request may still require:`,
      [
        `device information;`,
        `screenshots;`,
        `confirmation of settings;`,
        `network checks;`,
        `reasonable troubleshooting; or`,
        `information from an eSIM or network provider.`,
      ],
      `Marking a non-urgent complaint as urgent does not guarantee immediate resolution.`,
    ],
  },
  {
    title: '9. Acknowledgement',
    blocks: [
      `We aim to acknowledge an ordinary complaint within five business days after receipt.`,
      `The acknowledgement may include:`,
      [
        `confirmation that the complaint has been registered;`,
        `a reference number;`,
        `a summary of the issue;`,
        `the name or role of the person handling it;`,
        `a request for additional information; and`,
        `an indicative response timeframe.`,
      ],
      `If we provide a full resolution within the acknowledgement period, a separate acknowledgement may not be necessary.`,
      `Data protection complaints will in all cases be acknowledged within any mandatory legal period that applies.`,
    ],
  },
  {
    title: '10. Initial Assessment',
    blocks: [
      `After receiving a complaint, we will determine:`,
      [
        `what happened;`,
        `which service or transaction is affected;`,
        `whether urgent action is required;`,
        `whether additional information is needed;`,
        `which ArvoSim policy applies;`,
        `whether a third-party provider must be contacted;`,
        `whether there is a security or fraud concern;`,
        `whether personal data is involved; and`,
        `the appropriate person or team to investigate.`,
      ],
      `We may separate a complaint into multiple issues where this helps provide a clearer response.`,
    ],
  },
  {
    title: '11. Investigation',
    blocks: [
      `Depending on the complaint, we may review:`,
      [
        `Account information;`,
        `Order records;`,
        `delivery records;`,
        `QR-code dispatch records;`,
        `eSIM provisioning data;`,
        `activation and usage records;`,
        `Wallet transactions;`,
        `payment-provider information;`,
        `refund records;`,
        `Chargebacks;`,
        `security logs;`,
        `customer support correspondence;`,
        `device and configuration information;`,
        `information supplied by an eSIM provider;`,
        `information supplied by a mobile network; and`,
        `evidence provided by the complainant.`,
      ],
      `We will take reasonable steps to investigate fairly and will consider evidence supporting both the complainant's position and ArvoSim's position.`,
    ],
  },
  {
    title: '12. Cooperation with the Investigation',
    blocks: [
      `We may ask you to provide reasonable assistance, such as:`,
      [
        `confirming the affected device;`,
        `providing an error screenshot;`,
        `checking relevant device settings;`,
        `confirming whether the eSIM was installed or deleted;`,
        `attempting proportionate troubleshooting;`,
        `confirming a transaction;`,
        `verifying Account ownership; or`,
        `clarifying the remedy sought.`,
      ],
      `We will not require evidence that would be impossible or unreasonably difficult for an ordinary user to obtain.`,
      `A failure to cooperate may limit our ability to resolve a technical or factual issue, but it will not remove rights that apply under mandatory law.`,
    ],
  },
  {
    title: '13. Identity and Security Verification',
    blocks: [
      `Before discussing confidential information or providing certain remedies, we may need to verify:`,
      [
        `your identity;`,
        `Account ownership;`,
        `access to the registered email address;`,
        `authority to use a payment method;`,
        `entitlement to Wallet funds; or`,
        `authority to act for another person.`,
      ],
      `Verification measures will be proportionate to the nature and risk of the request.`,
      `We will never ask you by email to provide:`,
      [
        `a full payment-card number;`,
        `a card security code;`,
        `an online banking password; or`,
        `a one-time banking authentication code.`,
      ],
    ],
  },
  {
    title: '14. Third-Party Involvement',
    blocks: [
      `Some complaints may require information or action from:`,
      [
        `an eSIM provisioning provider;`,
        `a mobile network operator;`,
        `a payment provider;`,
        `a card issuer;`,
        `an email-delivery provider;`,
        `a hosting provider; or`,
        `another technical service provider.`,
      ],
      `We remain responsible for managing your complaint concerning the ArvoSim Service, but third-party involvement may extend the time required to establish technical facts.`,
      `Where appropriate, we will keep you informed of material delays.`,
    ],
  },
  {
    title: '15. Response Timeframes',
    blocks: [
      `We aim to provide a substantive response to an ordinary complaint within 15 business days after receiving sufficient information to investigate it.`,
      `We aim to issue a final response within 30 business days.`,
      `These are service targets rather than guaranteed statutory deadlines.`,
      `A complaint may take longer where:`,
      [
        `it is technically complex;`,
        `multiple transactions are involved;`,
        `information is required from a third party;`,
        `fraud or unauthorised activity is suspected;`,
        `extensive records must be reviewed;`,
        `the complainant has not yet provided required information;`,
        `legal advice is reasonably necessary; or`,
        `circumstances outside our reasonable control affect the investigation.`,
      ],
      `If we cannot provide a final response within 30 business days, we will aim to explain:`,
      [
        `why additional time is needed;`,
        `what remains under investigation;`,
        `whether information is required from you; and`,
        `when the next update is expected.`,
      ],
      `Where applicable law imposes a different or shorter timeframe, the legal requirement will take priority.`,
    ],
  },
  {
    title: '16. Keeping You Informed',
    blocks: [
      `During a prolonged investigation, we may provide updates concerning:`,
      [
        `the status of the complaint;`,
        `additional information required;`,
        `contact with a provider;`,
        `temporary measures taken;`,
        `estimated next steps; and`,
        `the reason for any material delay.`,
      ],
      `An update may not contain confidential security, fraud-prevention or third-party information that we are not permitted to disclose.`,
    ],
  },
  {
    title: '17. Temporary Measures',
    blocks: [
      `While a complaint is being investigated, we may take proportionate temporary action, including:`,
      [
        `resending a delivery email;`,
        `providing troubleshooting instructions;`,
        `reserving disputed Wallet funds;`,
        `pausing an unfulfilled Order;`,
        `preventing further use of a compromised eSIM;`,
        `temporarily restricting an Account;`,
        `escalating an urgent provider query; or`,
        `preserving relevant transaction and technical records.`,
      ],
      `A temporary measure does not determine the final outcome.`,
    ],
  },
  {
    title: '18. Possible Outcomes',
    blocks: [
      `Depending on the complaint, we may:`,
      [
        `provide an explanation;`,
        `apologise;`,
        `correct Account information;`,
        `correct a Wallet entry;`,
        `resend a QR code;`,
        `repair or reprovision an eSIM;`,
        `issue a replacement eSIM;`,
        `provide an equivalent Plan;`,
        `restore funds to the Wallet Balance;`,
        `refund an eligible Wallet Top-Up;`,
        `return an eligible closing balance;`,
        `provide a full or proportionate price reduction;`,
        `remove an incorrect Account restriction;`,
        `confirm that the original decision was correct;`,
        `improve internal guidance;`,
        `refer a technical issue to a provider; or`,
        `take another remedy required by applicable law.`,
      ],
      `The remedy will depend on:`,
      [
        `the nature of the failure;`,
        `whether the eSIM was used;`,
        `the benefit received;`,
        `the evidence available;`,
        `the practical remedy still available;`,
        `the relevant ArvoSim policies; and`,
        `applicable consumer law.`,
      ],
    ],
  },
  {
    title: '19. Financial Remedies',
    blocks: [
      `Where a financial remedy is approved, it will be handled in accordance with the Refund and Cancellation Policy and Payment and Wallet Policy.`,
      `In particular:`,
      [
        `an approved voluntary eSIM refund will normally be restored to the Wallet Balance;`,
        `a qualifying Wallet Top-Up refund will normally be returned to the original payment method;`,
        `an eligible unused Cash-Funded Balance will be returned when the Account is permanently closed; and`,
        `Promotional Credit is not ordinarily redeemable for cash.`,
      ],
      `We will not deduct an administrative fee from an approved full refund unless a fee is expressly permitted by applicable law and the relevant contract.`,
    ],
  },
  {
    title: '20. Complaints About Non-Delivery',
    blocks: [
      `Where an eSIM was allegedly not delivered, we may review:`,
      [
        `whether the Order was accepted;`,
        `whether the QR-code email was sent;`,
        `the email address used;`,
        `any bounce or rejection notice;`,
        `spam or filtering issues;`,
        `whether the Plan remained available;`,
        `whether the Plan price was deducted; and`,
        `whether the email was resent.`,
      ],
      `Where delivery cannot be established or completed, we may:`,
      [
        `resend the email;`,
        `deliver to a verified replacement address;`,
        `issue a replacement eSIM;`,
        `provide an equivalent Plan; or`,
        `restore the Plan price to the Wallet Balance.`,
      ],
    ],
  },
  {
    title: '21. Complaints About Activation or Connectivity',
    blocks: [
      `For activation or connectivity complaints, we may consider:`,
      [
        `device compatibility;`,
        `whether the device is carrier-unlocked;`,
        `installation status;`,
        `APN settings;`,
        `data-roaming settings;`,
        `network selection;`,
        `destination coverage;`,
        `Supported Network availability;`,
        `activation records;`,
        `data-consumption records;`,
        `temporary outages;`,
        `provider fault reports; and`,
        `troubleshooting already completed.`,
      ],
      `A local variation in speed or coverage will not automatically establish that the eSIM is faulty.`,
      `A remedy may be appropriate where the Plan was materially unusable and the problem was attributable to the supplied eSIM or service.`,
    ],
  },
  {
    title: '22. Complaints About Data Usage',
    blocks: [
      `Where you dispute data consumption, we may review:`,
      [
        `provider usage records;`,
        `activation times;`,
        `session records;`,
        `remaining data;`,
        `device screenshots;`,
        `hotspot or tethering use;`,
        `background data activity;`,
        `software updates;`,
        `cloud backups; and`,
        `technical anomalies.`,
      ],
      `Network or provider records will normally be the primary evidence of consumption, but we will consider credible evidence of an error.`,
    ],
  },
  {
    title: '23. Complaints About Refund Decisions',
    blocks: [
      `If you disagree with a refund decision, you should explain:`,
      [
        `which part of the decision you dispute;`,
        `which facts you believe are incorrect;`,
        `whether relevant evidence was overlooked;`,
        `whether the eSIM was used;`,
        `what remedy you believe is appropriate; and`,
        `any new evidence supporting your position.`,
      ],
      `A complaint about a refund decision will be reviewed separately from the original decision where reasonably practicable.`,
    ],
  },
  {
    title: '24. Payment Complaints',
    blocks: [
      `Payment complaints may concern:`,
      [
        `a failed Top-Up;`,
        `a pending authorisation;`,
        `an incorrect amount;`,
        `a duplicate payment;`,
        `missing Wallet credit;`,
        `an unauthorised payment;`,
        `currency conversion;`,
        `a delayed refund;`,
        `a reversed payment;`,
        `a Chargeback; or`,
        `a negative Wallet Balance.`,
      ],
      `We may need to distinguish between:`,
      [
        `an amount received by ArvoSim;`,
        `a pending bank authorisation;`,
        `an issuer fee;`,
        `an exchange-rate difference;`,
        `a completed refund; and`,
        `a delay within the card issuer's systems.`,
      ],
      `Some banking or card-issuer matters may need to be addressed directly with the relevant financial institution.`,
    ],
  },
  {
    title: '25. Chargebacks',
    blocks: [
      `We encourage users who recognise a transaction but dispute the service outcome to contact us before initiating a Chargeback.`,
      `This gives us an opportunity to:`,
      [
        `investigate the complaint;`,
        `correct an error;`,
        `provide a refund where due;`,
        `identify the relevant transaction; and`,
        `avoid unnecessary Account restrictions.`,
      ],
      `However, nothing in this Policy prevents you from exercising rights available through your card issuer, Payment Provider or applicable law.`,
      `Where a Chargeback is already open, we may:`,
      [
        `provide relevant transaction evidence;`,
        `suspend the disputed Wallet funds;`,
        `place unfulfilled Orders on hold;`,
        `correct an established error;`,
        `cooperate with the Payment Provider; and`,
        `continue trying to resolve the underlying complaint directly.`,
      ],
      `You must not knowingly seek and retain both:`,
      [
        `a payment reversal; and`,
        `the corresponding Wallet credit or purchased benefit.`,
      ],
    ],
  },
  {
    title: '26. Complaints About Account Restrictions',
    blocks: [
      `If your Account, eSIM, Order or Wallet has been restricted, you may request a review.`,
      `Your complaint should explain:`,
      [
        `which restriction is disputed;`,
        `when it began;`,
        `why you believe it is incorrect;`,
        `whether your Account may have been compromised;`,
        `whether a payment was reversed; and`,
        `any relevant supporting information.`,
      ],
      `We may be unable to disclose detailed fraud-prevention methods or confidential provider information.`,
      `A restriction may remain in place during review where continued access would create a reasonable legal, payment, security or network risk.`,
    ],
  },
  {
    title: '27. Complaints About Account Closure',
    blocks: [
      `An Account cannot currently be closed through a self-service function.`,
      `Requests for closure must be sent to info@arvosim.com.`,
      `A complaint may be raised if:`,
      [
        `a closure request was not processed;`,
        `verification was unreasonably delayed;`,
        `a closing balance was calculated incorrectly;`,
        `an eligible refund was not initiated; or`,
        `information was retained without a clear explanation.`,
      ],
      `Before closing an Account, we may need to complete verification, settle pending Orders, resolve disputes and identify the source of Wallet funds.`,
    ],
  },
  {
    title: '28. Data Protection Complaints',
    blocks: [
      `A data protection complaint may concern:`,
      [
        `inaccurate personal data;`,
        `access to personal data;`,
        `deletion or retention;`,
        `direct marketing;`,
        `cookies;`,
        `an alleged unauthorised disclosure;`,
        `international transfers;`,
        `security;`,
        `a privacy-rights request;`,
        `automated processing; or`,
        `another use of personal data.`,
      ],
      `Data protection complaints should be clearly marked: Data Protection Complaint`,
      `We will:`,
      [
        `provide a clear method for making the complaint;`,
        `acknowledge it within 30 days at the latest;`,
        `take appropriate steps to investigate without undue delay;`,
        `make appropriate enquiries;`,
        `keep the complainant informed of material progress; and`,
        `communicate the outcome without undue delay.`,
      ],
      `Our general five-business-day acknowledgement target will normally apply, but the legal 30-day requirement remains the maximum applicable acknowledgement period.`,
      `Further information is provided in the Privacy Policy.`,
    ],
  },
  {
    title: '29. Complaint to the ICO',
    blocks: [
      `If you are dissatisfied with how we have handled a data protection complaint, you have the right to complain to the UK Information Commissioner's Office.`,
      `We encourage you to contact ArvoSim first so that we have an opportunity to investigate and correct the issue, but you do not need our permission before contacting the ICO.`,
      `The ICO can consider data protection matters. It does not resolve ordinary eSIM quality, Wallet or contractual disputes that do not involve personal data.`,
    ],
  },
  {
    title: '30. Final Response',
    blocks: [
      `When our investigation is complete, we will provide a final response on a durable medium, normally by email.`,
      `The final response should include, where appropriate:`,
      [
        `a summary of the complaint;`,
        `the material facts considered;`,
        `the outcome;`,
        `reasons for the decision;`,
        `any remedy offered;`,
        `any action required from you;`,
        `the expected remedy timeframe;`,
        `information about internal reconsideration;`,
        `information about applicable ADR arrangements; and`,
        `any other external escalation option that must be disclosed.`,
      ],
      `The response may omit confidential security controls, legally privileged material or third-party information that we are not authorised to disclose.`,
    ],
  },
  {
    title: '31. Internal Reconsideration',
    blocks: [
      `If you disagree with the final response, you may request one internal reconsideration.`,
      `The request should normally be submitted within 30 calendar days after the final response and should identify:`,
      [
        `the part of the decision disputed;`,
        `any factual or legal error;`,
        `information that was overlooked;`,
        `new evidence; and`,
        `the remedy requested.`,
      ],
      `Where reasonably practicable, the reconsideration will be handled by a person who was not solely responsible for the original final decision.`,
      `A reconsideration is not intended to repeat the entire investigation without a stated reason.`,
    ],
  },
  {
    title: '32. Outcome of Reconsideration',
    blocks: [
      `After reconsideration, we may:`,
      [
        `uphold the original outcome;`,
        `change the decision;`,
        `provide a different remedy;`,
        `request further information;`,
        `reopen part of the investigation; or`,
        `confirm that the internal complaint process is exhausted.`,
      ],
      `We will explain the result on a durable medium.`,
    ],
  },
  {
    title: '33. Alternative Dispute Resolution',
    blocks: [
      `Alternative Dispute Resolution, or ADR, is a method of resolving certain consumer disputes outside court with the involvement of an independent third party.`,
      `ArvoSim is not identifying a specific ADR provider in this Policy because:`,
      [
        `the competent provider may depend on the nature and value of the dispute;`,
        `ADR accreditation and legal requirements may change; and`,
        `we must not imply membership of or commitment to a scheme that has not been confirmed.`,
      ],
      `Where the internal complaint process is exhausted and applicable law requires ADR information, the final response will state:`,
      [
        `that ArvoSim has been unable to settle the complaint;`,
        `the name and website of a competent ADR provider or other applicable dispute-resolution arrangement;`,
        `whether ArvoSim is legally or contractually required to participate; and`,
        `whether ArvoSim is prepared to participate voluntarily.`,
      ],
      `The identification of an ADR provider does not itself mean that ArvoSim has agreed to participate unless the final response expressly confirms this or participation is legally required.`,
    ],
  },
  {
    title: '34. No Automatic Obligation to Use ADR',
    blocks: [
      `Unless required by law, a contract or an applicable scheme, neither party is automatically required under this Policy to submit a dispute to ADR.`,
      `Where both parties agree to use ADR, the process will be governed by:`,
      [
        `the applicable ADR provider's rules;`,
        `any legal requirements;`,
        `the scope of the agreement to participate; and`,
        `any binding effect properly accepted by the parties.`,
      ],
      `A Consumer will not be bound by a pre-dispute term requiring participation in a process where such a term would be unenforceable under applicable law.`,
    ],
  },
  {
    title: '35. Consumer Advice',
    blocks: [
      `UK Consumers may seek independent information about consumer rights from the Citizens Advice Consumer Service or another appropriate consumer-advice body.`,
      `Consumers located outside the United Kingdom may seek assistance from a competent consumer-protection organisation in their country of residence.`,
      `ArvoSim does not control the advice, eligibility rules or dispute procedures of independent organisations.`,
    ],
  },
  {
    title: '36. Court Proceedings',
    blocks: [
      `This Policy does not prevent either party from bringing court proceedings where legally entitled to do so.`,
      `Before commencing proceedings, the parties should, where reasonable:`,
      [
        `exchange sufficient information about the claim;`,
        `identify the remedy sought;`,
        `consider whether the dispute can be resolved directly;`,
        `consider proportionate ADR; and`,
        `comply with any applicable pre-action requirements.`,
      ],
      `Nothing in this section requires a user to delay urgent legal action where delay could prejudice a legal right.`,
      `The governing-law and jurisdiction provisions in the Terms and Conditions apply, subject to mandatory consumer protections.`,
    ],
  },
  {
    title: '37. Consumers Outside England and Wales',
    blocks: [
      `A Consumer resident in another part of the United Kingdom or another country may have mandatory rights to:`,
      [
        `bring proceedings in their place of residence;`,
        `use a local consumer-protection body;`,
        `rely on mandatory local consumer law; or`,
        `access another dispute-resolution procedure.`,
      ],
      `Nothing in this Policy removes rights that cannot legally be excluded.`,
    ],
  },
  {
    title: '38. Business Users',
    blocks: [
      `A Business User should submit complaints through the same email address unless a separate written business agreement provides another procedure.`,
      `Consumer-specific rights and procedures apply only where the complainant qualifies as a Consumer.`,
      `Business disputes may be subject to:`,
      [
        `the relevant business agreement;`,
        `the Terms and Conditions;`,
        `agreed commercial dispute procedures; and`,
        `the exclusive jurisdiction provisions applicable to Business Users.`,
      ],
    ],
  },
  {
    title: '39. Repeated or Duplicate Complaints',
    blocks: [
      `Where substantially the same complaint has already received a final response and no material new information is provided, we may:`,
      [
        `refer the complainant to the previous response;`,
        `decline to repeat the investigation;`,
        `address only the new issue; or`,
        `confirm that the internal complaint process is exhausted.`,
      ],
      `We will not classify a complaint as repetitive merely because the complainant disagrees with the outcome or requests a legitimate reconsideration.`,
    ],
  },
  {
    title: '40. Abusive or Threatening Communications',
    blocks: [
      `We understand that complaints may involve frustration.`,
      `However, users must not:`,
      [
        `threaten violence;`,
        `harass staff;`,
        `use discriminatory abuse;`,
        `send malicious content;`,
        `deliberately overwhelm communication channels;`,
        `impersonate another person;`,
        `falsify evidence; or`,
        `use complaints to facilitate fraud.`,
      ],
      `Where communications become abusive, we may:`,
      [
        `request that communication remain respectful;`,
        `limit communications to writing;`,
        `designate a single contact channel;`,
        `restrict unnecessary repeated messages; or`,
        `report credible threats or unlawful conduct.`,
      ],
      `We will continue to address the substantive complaint where reasonably possible.`,
    ],
  },
  {
    title: '41. Manifestly Unfounded or Abusive Privacy Complaints',
    blocks: [
      `A privacy complaint will not be rejected merely because it is inconvenient, critical or difficult.`,
      `Where applicable law permits action in response to a manifestly unfounded or excessive request, we will consider the specific circumstances and document the reasons for our decision.`,
      `Any fee, refusal or restriction will be applied only where legally permitted.`,
    ],
  },
  {
    title: '42. Confidentiality',
    blocks: [
      `We will handle complaints with appropriate confidentiality.`,
      `Information may be shared only where reasonably necessary with:`,
      [
        `staff handling the complaint;`,
        `eSIM or network providers;`,
        `payment providers;`,
        `professional advisers;`,
        `regulators;`,
        `courts;`,
        `law-enforcement authorities; or`,
        `another authorised recipient.`,
      ],
      `Personal data will be processed in accordance with the Privacy Policy.`,
    ],
  },
  {
    title: '43. Complaint Records',
    blocks: [
      `We may retain records of:`,
      [
        `the complaint;`,
        `evidence supplied;`,
        `correspondence;`,
        `investigation steps;`,
        `provider responses;`,
        `internal decisions;`,
        `the remedy;`,
        `the final response; and`,
        `any reconsideration or external escalation.`,
      ],
      `Records may be retained where reasonably necessary for:`,
      [
        `complaint management;`,
        `service improvement;`,
        `accounting;`,
        `fraud prevention;`,
        `legal compliance;`,
        `Chargebacks;`,
        `regulatory requests; and`,
        `legal claims.`,
      ],
      `Retention is governed by the Privacy Policy.`,
    ],
  },
  {
    title: '44. Service Improvement',
    blocks: [
      `We may analyse complaints to identify:`,
      [
        `recurring technical failures;`,
        `delivery delays;`,
        `confusing Plan descriptions;`,
        `payment problems;`,
        `refund trends;`,
        `accessibility barriers;`,
        `provider performance;`,
        `support-training needs; and`,
        `possible policy improvements.`,
      ],
      `Where possible, reporting used for service improvement will be aggregated or anonymised.`,
    ],
  },
  {
    title: '45. No Admission of Liability',
    blocks: [
      `An investigation, apology, goodwill credit, replacement or voluntary resolution does not by itself constitute an admission of legal liability.`,
      `This does not prevent a communication from expressly accepting responsibility where appropriate.`,
    ],
  },
  {
    title: '46. Changes to this Policy',
    blocks: [
      `We may update this Policy to reflect changes to:`,
      [
        `the Service;`,
        `complaint processes;`,
        `eSIM providers;`,
        `payment providers;`,
        `ADR arrangements;`,
        `data protection requirements;`,
        `consumer law; or`,
        `our business operations.`,
      ],
      `The updated version will be published on arvosim.com with a revised "Last updated" date.`,
      `A change will not retrospectively reduce rights relating to a complaint already submitted.`,
    ],
  },
  {
    title: '47. Contact Information',
    blocks: [
      `Complaints, reconsideration requests and dispute-related correspondence may be directed to ARVO LINE LTD, company number 17221404, Dept 6800, 196 High Road, Wood Green, London, United Kingdom, N22 8HH.`,
      `Email: info@arvosim.com. Website: arvosim.com.`,
    ],
  },
];

export default function ComplaintsPage() {
  return (
    <PolicyPage
      title="Complaints and Dispute Resolution Policy"
      lastUpdated="31 July 2026"
      intro="This Complaints and Dispute Resolution Policy explains how you may raise a complaint concerning ArvoSim and how we will review, investigate and respond to it. Our aim is to resolve complaints fairly, promptly and proportionately before they develop into formal disputes."
      sections={sections}
    />
  );
}
