import { PolicyPage, type PolicySection } from '@/components/sections/PolicyPage';

const sections: PolicySection[] = [
  {
    title: '1. About this Policy',
    blocks: [
      `This Acceptable Use Policy sets out the rules that apply when you access or use:`,
      [
        `the ArvoSim Website;`,
        `an ArvoSim Account;`,
        `the ArvoSim Balance;`,
        `an eSIM or eSIM Plan;`,
        `mobile data connectivity supplied through ArvoSim;`,
        `customer support; or`,
        `any other ArvoSim feature or service.`,
      ],
      `This Policy is intended to:`,
      [
        `protect users and their Accounts;`,
        `prevent fraud and unlawful activity;`,
        `protect mobile networks and technical systems;`,
        `preserve fair access to connectivity;`,
        `prevent misuse of Balance funds, refunds and promotions; and`,
        `ensure that the Service is used only for its intended purpose.`,
      ],
      `This Policy forms part of the ArvoSim Terms and Conditions and should be read together with our:`,
      [
        `Terms and Conditions;`,
        `Payment and Balance Policy;`,
        `eSIM Delivery and Activation Policy;`,
        `Refund and Cancellation Policy;`,
        `Privacy Policy; and`,
        `Complaints and Dispute Resolution Policy.`,
      ],
      `ArvoSim is operated by ELVORIN LTD, company number 17344051, Suite 709, Avicenna House, 258–262 Romford Road, London, E7 9HZ, United Kingdom. Email: info@arvosim.com. Website: arvosim.com.`,
      `In this Policy, "ArvoSim", "we", "us" and "our" refer to ELVORIN LTD.`,
    ],
  },
  {
    title: '2. Who Must Comply',
    blocks: [
      `This Policy applies to:`,
      [
        `registered Account holders;`,
        `users of an ArvoSim eSIM;`,
        `persons accessing the Website;`,
        `persons using an eSIM through another user's device or hotspot;`,
        `persons acting on behalf of a Business User; and`,
        `anyone who accesses or benefits from the Service through an Account.`,
      ],
      `The Account holder is responsible for taking reasonable steps to ensure that anyone permitted to use the Account, device, eSIM or data connection complies with this Policy.`,
    ],
  },
  {
    title: '3. Permitted Use',
    blocks: [
      `The Service may be used for lawful personal or authorised business connectivity consistent with:`,
      [
        `the purchased Plan;`,
        `its destination and coverage;`,
        `its data allowance and validity period;`,
        `applicable network restrictions;`,
        `this Policy;`,
        `the Terms and Conditions; and`,
        `applicable law.`,
      ],
      `Ordinary permitted activities may include:`,
      [
        `web browsing;`,
        `email;`,
        `internet-based messaging;`,
        `navigation;`,
        `social media;`,
        `video or audio calls;`,
        `streaming;`,
        `downloading applications;`,
        `remote work;`,
        `access to cloud services; and`,
        `personal hotspot or tethering where supported by the relevant Plan and network.`,
      ],
      `Permitted use does not include any activity prohibited by this Policy merely because it is technically possible.`,
    ],
  },
  {
    title: '4. Lawful Use',
    blocks: [
      `You must use the Service in accordance with all laws and regulations that apply:`,
      [
        `in the United Kingdom;`,
        `in your country of residence;`,
        `in the country where the eSIM is used;`,
        `in the country where the relevant conduct has an effect; and`,
        `to the relevant mobile network, payment or communications service.`,
      ],
      `You must not use the Service to commit, facilitate, encourage, conceal or assist:`,
      [
        `fraud;`,
        `theft;`,
        `unauthorised access;`,
        `cybercrime;`,
        `harassment;`,
        `exploitation;`,
        `intellectual property infringement;`,
        `sanctions evasion;`,
        `unlawful surveillance;`,
        `distribution of unlawful content; or`,
        `any other criminal or unlawful activity.`,
      ],
    ],
  },
  {
    title: '5. Personal and Authorised Business Use',
    blocks: [
      `Unless ArvoSim has agreed otherwise in writing, eSIM Plans are intended for the Account holder's own personal or internal business use.`,
      `You must not:`,
      [
        `resell an eSIM;`,
        `sell access to the data connection;`,
        `sublicense or redistribute a Plan;`,
        `operate as an unauthorised connectivity reseller;`,
        `package the Service into another commercial offering;`,
        `advertise an ArvoSim eSIM for resale;`,
        `transfer Balance to customers or third parties; or`,
        `use ArvoSim branding to suggest an authorised reseller relationship.`,
      ],
      `Permitting a family member, colleague or travelling companion to use a personal hotspot does not by itself constitute resale, provided that:`,
      [
        `no payment is collected;`,
        `the use remains reasonable;`,
        `the relevant Plan permits tethering; and`,
        `this Policy is followed.`,
      ],
    ],
  },
  {
    title: '6. Account Security',
    blocks: [
      `You must take reasonable steps to protect your Account.`,
      `You must not:`,
      [
        `share your password publicly;`,
        `sell or transfer your Account;`,
        `allow an unknown person to use your Account;`,
        `provide access in return for payment;`,
        `use credentials obtained without permission;`,
        `attempt to access another user's Account;`,
        `bypass login, authentication or security controls; or`,
        `conceal unauthorised access.`,
      ],
      `You must notify info@arvosim.com promptly if you believe that:`,
      [
        `your Account has been compromised;`,
        `your email Account has been accessed without permission;`,
        `an unknown person has used your Balance;`,
        `an eSIM QR code has been exposed; or`,
        `an unauthorised transaction has occurred.`,
      ],
    ],
  },
  {
    title: '7. eSIM and QR-Code Security',
    blocks: [
      `An eSIM QR code and any manual activation information are confidential.`,
      `You must not:`,
      [
        `publish a QR code;`,
        `post it on social media;`,
        `sell it;`,
        `share it with an unauthorised person;`,
        `scan it on several devices;`,
        `copy it for redistribution;`,
        `use it to create cloned or duplicate profiles;`,
        `attempt to extract protected provisioning credentials; or`,
        `interfere with the eSIM provisioning process.`,
      ],
      `You are responsible for protecting the email Account to which the QR code is delivered.`,
      `If an eSIM is compromised because the QR code was knowingly shared or inadequately protected, ArvoSim may be unable to provide a free replacement or refund.`,
    ],
  },
  {
    title: '8. Payment Fraud',
    blocks: [
      `You must not use the Service with:`,
      [
        `a stolen payment card;`,
        `a compromised payment method;`,
        `payment details used without the owner's permission;`,
        `a false identity;`,
        `falsified billing information;`,
        `manipulated authentication information; or`,
        `funds obtained through unlawful activity.`,
      ],
      `You must not:`,
      [
        `test stolen card details;`,
        `conduct card-verification activity;`,
        `repeatedly attempt payments using different compromised cards;`,
        `instruct another person to make an unauthorised Top-Up;`,
        `conceal the true source of funds; or`,
        `use ArvoSim to facilitate payment laundering.`,
      ],
      `We may delay, decline, reverse or investigate a payment where reasonable fraud concerns arise.`,
    ],
  },
  {
    title: '9. Balance Abuse',
    blocks: [
      `You must not use the Balance to:`,
      [
        `transfer value between unrelated persons;`,
        `sell or exchange Balance;`,
        `conceal the origin of funds;`,
        `process payments for another business;`,
        `evade payment controls;`,
        `create artificial transaction volume;`,
        `exploit exchange-rate differences;`,
        `obtain cash through false Account-closure requests;`,
        `repeatedly Top-Up and request withdrawal without genuine use of the Service; or`,
        `use the Balance for any purpose other than purchasing eligible ArvoSim services.`,
      ],
      `The Balance is closed-loop Account credit and must not be treated as a general payment or money-transfer service.`,
    ],
  },
  {
    title: '10. Refund and Chargeback Abuse',
    blocks: [
      `You must not:`,
      [
        `claim that an eSIM was unused after data was consumed;`,
        `provide false screenshots or technical information;`,
        `delete an eSIM and falsely claim that it was never delivered;`,
        `request a refund from ArvoSim and simultaneously seek a Chargeback for the same amount;`,
        `retain Balance credit after the related payment has been reversed;`,
        `falsely report an authorised payment as unauthorised;`,
        `make repeated purchases primarily to obtain refunds;`,
        `use a Plan and then claim a change-of-mind refund; or`,
        `manipulate installation, activation or usage records.`,
      ],
      `A genuine refund request, complaint or Chargeback made in good faith will not be treated as abuse merely because ArvoSim disputes it.`,
    ],
  },
  {
    title: '11. Promotion and Referral Abuse',
    blocks: [
      `Where ArvoSim offers Promotional Credit, discount codes, referral benefits or other incentives, you must not:`,
      [
        `create fake Accounts;`,
        `create multiple Accounts for the same person to obtain repeated benefits;`,
        `use fictitious identities;`,
        `refer yourself through another Account;`,
        `use automated registrations;`,
        `buy or sell referral activity;`,
        `manipulate eligibility conditions;`,
        `create sham transactions;`,
        `cancel transactions after obtaining a reward;`,
        `use stolen personal or payment information; or`,
        `otherwise undermine the legitimate purpose of the promotion.`,
      ],
      `We may cancel Promotional Credit or disqualify an Account where a benefit was obtained through error, fraud or abuse.`,
      `Cash-Funded Balance will not be removed merely because Promotional Credit is cancelled, except where the cash balance itself resulted from fraud or payment reversal.`,
    ],
  },
  {
    title: '12. Unauthorised Access and Hacking',
    blocks: [
      `You must not attempt to gain unauthorised access to:`,
      [
        `the Website;`,
        `another Account;`,
        `administrative systems;`,
        `databases;`,
        `Balance records;`,
        `payment systems;`,
        `eSIM provisioning systems;`,
        `network infrastructure;`,
        `source code;`,
        `API credentials; or`,
        `any other protected system or data.`,
      ],
      `Prohibited conduct includes:`,
      [
        `password attacks;`,
        `credential stuffing;`,
        `brute-force attempts;`,
        `exploitation of security vulnerabilities;`,
        `bypassing access controls;`,
        `privilege escalation;`,
        `session hijacking;`,
        `API abuse;`,
        `injection attacks;`,
        `unauthorised scraping of protected data; and`,
        `use of stolen tokens or credentials.`,
      ],
    ],
  },
  {
    title: '13. Malware and Harmful Code',
    blocks: [
      `You must not use the Service to create, store, send, distribute, operate or control:`,
      [
        `malware;`,
        `ransomware;`,
        `spyware;`,
        `viruses;`,
        `worms;`,
        `trojans;`,
        `botnets;`,
        `credential-stealing tools;`,
        `destructive code;`,
        `malicious scripts;`,
        `command-and-control infrastructure; or`,
        `software intended to interfere with another system.`,
      ],
      `You must not use ArvoSim connectivity to infect, compromise, damage or control a device, system or network without lawful authorisation.`,
    ],
  },
  {
    title: '14. Network Attacks and Interference',
    blocks: [
      `You must not use the Service to conduct or assist:`,
      [
        `denial-of-service attacks;`,
        `distributed denial-of-service attacks;`,
        `port scanning without authorisation;`,
        `vulnerability scanning without authorisation;`,
        `packet flooding;`,
        `traffic amplification;`,
        `network probing;`,
        `interception of communications;`,
        `spoofing;`,
        `routing manipulation;`,
        `DNS abuse;`,
        `intrusion attempts; or`,
        `disruption of another person's connectivity.`,
      ],
      `You must not intentionally impair, overload, damage or reduce the availability of:`,
      [
        `a mobile network;`,
        `the ArvoSim Website;`,
        `a provider's system;`,
        `another user's service; or`,
        `telecommunications infrastructure.`,
      ],
    ],
  },
  {
    title: '15. Spam and Bulk Communications',
    blocks: [
      `You must not use the Service to send or facilitate:`,
      [
        `unsolicited bulk email;`,
        `mass messaging;`,
        `spam;`,
        `phishing messages;`,
        `fraudulent advertisements;`,
        `scam communications;`,
        `bulk automated messages;`,
        `deceptive links;`,
        `malicious attachments; or`,
        `communications sent in breach of applicable marketing or privacy law.`,
      ],
      `You must not operate:`,
      [
        `a bulk messaging system;`,
        `an auto-dialler;`,
        `an unattended messaging gateway;`,
        `a spam relay;`,
        `a SIM box;`,
        `a SIM farm; or`,
        `comparable high-volume communications infrastructure.`,
      ],
    ],
  },
  {
    title: '16. Machine-to-Machine and Automated Use',
    blocks: [
      `Unless the relevant Plan expressly permits it or ArvoSim agrees in writing, you must not use an eSIM:`,
      [
        `in unattended machine-to-machine equipment;`,
        `in industrial telemetry equipment;`,
        `in permanent monitoring hardware;`,
        `in vehicle tracking fleets;`,
        `in routers serving unrelated third parties;`,
        `in vending or payment terminals;`,
        `in automated scraping systems;`,
        `in large device farms;`,
        `in proxy farms;`,
        `in click farms;`,
        `in automated traffic-generation systems; or`,
        `as permanent infrastructure rather than ordinary travel connectivity.`,
      ],
      `Normal personal use of an eSIM in a compatible smartphone, tablet, laptop, hotspot device or supported router is not prohibited solely because the device performs ordinary background functions.`,
    ],
  },
  {
    title: '17. Excessive or Disruptive Network Use',
    blocks: [
      `You must not use the Service in a manner that unreasonably:`,
      [
        `congests the underlying network;`,
        `reduces service quality for other users;`,
        `consumes disproportionate network capacity;`,
        `bypasses Plan restrictions;`,
        `creates sustained abnormal traffic;`,
        `interferes with network management; or`,
        `uses the Plan in a way materially different from its intended purpose.`,
      ],
      `Examples may include:`,
      [
        `continuously transferring exceptionally large files for extended periods;`,
        `operating high-traffic public servers;`,
        `running peer-to-peer distribution at a disruptive scale;`,
        `maintaining continuous automated connections across many devices;`,
        `operating a commercial public hotspot;`,
        `hosting high-volume gaming or media servers; or`,
        `generating artificial traffic without a legitimate user purpose.`,
      ],
      `High data usage by itself will not automatically be treated as abuse where it is consistent with the purchased Plan and does not unreasonably impair the network.`,
    ],
  },
  {
    title: '18. Fair-Use and Network-Management Rules',
    blocks: [
      `Some Plans may be subject to:`,
      [
        `fair-use thresholds;`,
        `daily high-speed allowances;`,
        `speed reductions;`,
        `tethering restrictions;`,
        `network-priority rules;`,
        `traffic-management measures; or`,
        `restrictions imposed by the relevant network provider.`,
      ],
      `Where material restrictions are known to ArvoSim, they should be described in the Plan information or supporting documentation.`,
      `You must not attempt to:`,
      [
        `circumvent a fair-use threshold;`,
        `conceal usage to avoid network management;`,
        `manipulate a device identifier;`,
        `repeatedly reset a Plan;`,
        `route traffic through multiple Accounts to avoid limits;`,
        `interfere with throttling controls; or`,
        `exploit a technical error to obtain service beyond the purchased entitlement.`,
      ],
      `Network-management measures must not be interpreted as permission for ArvoSim to reduce a fixed Plan allowance contrary to its description.`,
    ],
  },
  {
    title: '19. Tethering and Hotspot Use',
    blocks: [
      `Personal tethering or hotspot use is permitted where supported by:`,
      [
        `the relevant eSIM Plan;`,
        `the user's device; and`,
        `the applicable mobile network.`,
      ],
      `You must not use tethering to:`,
      [
        `resell internet access;`,
        `operate a commercial public hotspot;`,
        `provide permanent connectivity to unrelated third parties;`,
        `bypass a network restriction;`,
        `run a prohibited automated system; or`,
        `create unreasonable network congestion.`,
      ],
      `A provider may technically restrict tethering for a particular Plan. Such a restriction does not necessarily indicate a fault with the eSIM.`,
    ],
  },
  {
    title: '20. Servers, Proxies and Relays',
    blocks: [
      `Unless expressly authorised, you must not use the Service to operate:`,
      [
        `an open proxy;`,
        `a public VPN exit node;`,
        `a Tor exit node;`,
        `an anonymous relay;`,
        `an open mail relay;`,
        `a public web server;`,
        `a public game server;`,
        `a public file-distribution server;`,
        `a cryptocurrency mining operation;`,
        `a command-and-control server; or`,
        `another service that exposes the mobile connection for unrestricted third-party use.`,
      ],
      `Ordinary use of a reputable personal VPN for privacy or secure remote work is not prohibited, provided that the VPN is used lawfully and does not breach this Policy.`,
    ],
  },
  {
    title: '21. Illegal or Harmful Content',
    blocks: [
      `You must not knowingly use the Service to create, access, store, distribute or promote content where doing so is unlawful.`,
      `This may include content involving:`,
      [
        `child sexual abuse or exploitation;`,
        `terrorist activity;`,
        `credible threats of violence;`,
        `unlawful incitement;`,
        `trafficking;`,
        `fraud;`,
        `unlawful sale of controlled goods;`,
        `malicious code;`,
        `non-consensual intimate material;`,
        `unlawful harassment; or`,
        `material whose possession or distribution is prohibited by applicable law.`,
      ],
      `ArvoSim does not generally select or control content transmitted through third-party mobile networks, but may act where credible evidence of unlawful use is received.`,
    ],
  },
  {
    title: '22. Harassment and Abuse',
    blocks: [
      `You must not use the Service to:`,
      [
        `threaten another person;`,
        `stalk or unlawfully monitor another person;`,
        `repeatedly harass another person;`,
        `impersonate another person for harmful purposes;`,
        `publish personal information unlawfully;`,
        `coordinate targeted abuse;`,
        `send malicious or intimidating communications; or`,
        `facilitate coercion or exploitation.`,
      ],
      `This section does not prohibit lawful criticism, journalism, public-interest reporting or legitimate dispute resolution.`,
    ],
  },
  {
    title: '23. Intellectual Property',
    blocks: [
      `You must not use the Service to knowingly infringe:`,
      [
        `copyright;`,
        `trade marks;`,
        `patents;`,
        `database rights;`,
        `trade secrets;`,
        `software licences;`,
        `confidential information; or`,
        `other intellectual property rights.`,
      ],
      `You must not use ArvoSim's Website, brand or content to:`,
      [
        `create a misleading copy of the Website;`,
        `impersonate ArvoSim;`,
        `operate a phishing page;`,
        `distribute unauthorised copies;`,
        `suggest sponsorship or approval that does not exist; or`,
        `deceive users about the source of an eSIM.`,
      ],
    ],
  },
  {
    title: '24. Privacy and Unlawful Surveillance',
    blocks: [
      `You must not use the Service to:`,
      [
        `intercept communications without lawful authority;`,
        `monitor another person without a lawful basis;`,
        `deploy spyware;`,
        `collect credentials through deception;`,
        `conduct unlawful location tracking;`,
        `access private data without permission;`,
        `violate applicable data protection law; or`,
        `disclose personal data unlawfully.`,
      ],
      `Legitimate use of navigation, device-location or security functionality is permitted where the user has appropriate authority and complies with applicable law.`,
    ],
  },
  {
    title: '25. Sanctions and Prohibited Jurisdictions',
    blocks: [
      `You must not use or obtain the Service where doing so would cause ArvoSim, a payment provider, an eSIM provider or a mobile network to breach applicable:`,
      [
        `financial sanctions;`,
        `trade sanctions;`,
        `export controls;`,
        `telecommunications restrictions;`,
        `asset-freezing requirements; or`,
        `other legal prohibitions.`,
      ],
      `You must not:`,
      [
        `act for a sanctioned person or entity;`,
        `conceal the involvement of a restricted person;`,
        `use false location or identity information to evade sanctions controls;`,
        `route payment through another person to avoid a restriction;`,
        `resell the Service into a prohibited jurisdiction; or`,
        `use the Service in connection with a prohibited transaction or activity.`,
      ],
      `Plan availability on the Website does not override applicable legal restrictions.`,
    ],
  },
  {
    title: '26. Misrepresentation and Impersonation',
    blocks: [
      `You must not:`,
      [
        `impersonate another person;`,
        `create an Account using false identity information;`,
        `falsely claim to represent a business;`,
        `impersonate ArvoSim staff;`,
        `alter an ArvoSim communication to mislead another person;`,
        `use the Service to create fake support or payment messages;`,
        `submit false documents; or`,
        `misrepresent material facts during verification, support, complaints or refund processing.`,
      ],
      `Use of a nickname or ordinary display name is not prohibited where it does not mislead ArvoSim or another person about a material fact.`,
    ],
  },
  {
    title: '27. Interference with the Service',
    blocks: [
      `You must not:`,
      [
        `overload the Website;`,
        `bypass rate limits;`,
        `scrape the Website at an unreasonable or disruptive scale;`,
        `use bots to place Orders;`,
        `interfere with checkout;`,
        `manipulate prices;`,
        `exploit an obvious error;`,
        `alter Balance records;`,
        `circumvent security controls;`,
        `obstruct another user's access;`,
        `disable technical protections; or`,
        `test production systems without authorisation.`,
      ],
      `If you discover a suspected security vulnerability, you should report it responsibly to info@arvosim.com and must not exploit it, access unrelated data or publicly disclose it in a manner that creates avoidable harm.`,
    ],
  },
  {
    title: '28. Multiple Accounts',
    blocks: [
      `You must not create or operate multiple Accounts for the purpose of:`,
      [
        `evading a suspension;`,
        `bypassing transaction limits;`,
        `repeatedly claiming promotional benefits;`,
        `concealing fraudulent activity;`,
        `avoiding a negative balance;`,
        `obtaining multiple refunds;`,
        `circumventing sanctions screening; or`,
        `frustrating an investigation.`,
      ],
      `A person may have more than one Account for a legitimate reason only where this does not create fraud, security, payment or promotional abuse.`,
      `We may ask the user to consolidate or verify related Accounts.`,
    ],
  },
  {
    title: '29. Circumvention',
    blocks: [
      `You must not attempt to bypass or undermine:`,
      [
        `Account restrictions;`,
        `payment verification;`,
        `3D Secure;`,
        `fraud controls;`,
        `fair-use limits;`,
        `device restrictions;`,
        `Plan validity;`,
        `geographical restrictions;`,
        `network-management measures;`,
        `sanctions screening;`,
        `refund controls;`,
        `security systems; or`,
        `a suspension or termination decision.`,
      ],
      `Use of a VPN, roaming function or ordinary privacy tool is not prohibited merely because it changes the apparent internet location. It becomes prohibited where it is used to conceal fraud, evade legal restrictions or circumvent the Service rules.`,
    ],
  },
  {
    title: '30. Investigation of Suspected Misuse',
    blocks: [
      `Where we reasonably suspect a breach, we may review information available to us, including:`,
      [
        `Account records;`,
        `Balance transactions;`,
        `payment status;`,
        `Chargebacks;`,
        `Order history;`,
        `eSIM provisioning records;`,
        `activation and data-usage records;`,
        `IP and device information;`,
        `security logs;`,
        `support communications;`,
        `related Accounts; and`,
        `information supplied by service providers.`,
      ],
      `We will process personal data in accordance with the Privacy Policy and applicable law.`,
      `We do not undertake a general obligation to inspect the content of users' internet communications.`,
    ],
  },
  {
    title: '31. Cooperation with an Investigation',
    blocks: [
      `We may ask you to provide reasonable information needed to:`,
      [
        `verify Account ownership;`,
        `confirm authority to use a payment method;`,
        `investigate a disputed transaction;`,
        `determine whether an eSIM was compromised;`,
        `assess a suspected breach;`,
        `resolve a security incident; or`,
        `satisfy a legal requirement.`,
      ],
      `Failure to provide reasonably necessary information may result in temporary restrictions where we cannot safely continue providing the Service.`,
      `We will not request passwords, full card numbers, card security codes or banking authentication codes by email.`,
    ],
  },
  {
    title: '32. Protective Measures',
    blocks: [
      `Where reasonably necessary to protect users, networks, payment systems or the Service, we may:`,
      [
        `delay an Order;`,
        `request verification;`,
        `restrict a payment method;`,
        `freeze disputed Balance funds;`,
        `restrict a Plan;`,
        `reduce access to an affected feature;`,
        `suspend an eSIM;`,
        `suspend an Account;`,
        `remove Promotional Credit;`,
        `cancel an unfulfilled Order;`,
        `block a device, IP address or Account;`,
        `prevent creation of replacement Accounts; or`,
        `terminate the relationship.`,
      ],
      `The measure selected will depend on:`,
      [
        `the seriousness of the suspected breach;`,
        `the urgency of the risk;`,
        `whether the conduct is continuing;`,
        `potential harm to others;`,
        `the reliability of the available evidence;`,
        `whether a less restrictive measure would be effective; and`,
        `applicable legal or provider requirements.`,
      ],
    ],
  },
  {
    title: '33. Immediate Suspension',
    blocks: [
      `We may act without advance notice where delay could reasonably:`,
      [
        `expose another person to harm;`,
        `allow continued fraud;`,
        `compromise a payment method;`,
        `damage a network or system;`,
        `enable unlawful activity;`,
        `undermine an investigation;`,
        `permit dissipation of disputed funds;`,
        `breach sanctions;`,
        `create a security incident; or`,
        `cause ArvoSim or a provider to breach law.`,
      ],
      `Where legally and operationally possible, we will provide an explanation after the immediate risk has been addressed.`,
    ],
  },
  {
    title: '34. Notice and Opportunity to Respond',
    blocks: [
      `For less urgent or remediable breaches, we may:`,
      [
        `notify you of the concern;`,
        `request an explanation;`,
        `require the activity to stop;`,
        `provide a reasonable period to correct the issue; or`,
        `issue a warning.`,
      ],
      `We are not required to provide advance notice where:`,
      [
        `the breach is serious;`,
        `the conduct appears fraudulent or criminal;`,
        `the Account has been compromised;`,
        `immediate action is required by law or a provider; or`,
        `notice would undermine security or fraud prevention.`,
      ],
    ],
  },
  {
    title: '35. Effect on Orders and Balance',
    blocks: [
      `Where an Account is restricted:`,
      [
        `pending Orders may be delayed;`,
        `unfulfilled Orders may be cancelled;`,
        `the relevant Plan price may be restored to the Balance;`,
        `disputed funds may remain unavailable while investigated;`,
        `a reversed payment may be deducted;`,
        `Promotional Credit obtained through abuse may be removed; and`,
        `legitimate Cash-Funded Balance will be handled in accordance with the Terms and Conditions and Payment and Balance Policy.`,
      ],
      `A breach of this Policy does not automatically allow ArvoSim to confiscate legitimate Cash-Funded Balance.`,
      `Any deduction, withholding or refusal of refund must have a contractual or legal basis and be proportionate to the circumstances.`,
    ],
  },
  {
    title: '36. Refunds Following a Breach',
    blocks: [
      `A refund may be refused where:`,
      [
        `the Service was consumed through prohibited use;`,
        `the user seeks to benefit from their own fraud;`,
        `payment was reversed;`,
        `the request is abusive; or`,
        `applicable contractual or legal rules permit refusal.`,
      ],
      `However, we will not exclude:`,
      [
        `mandatory consumer rights;`,
        `a valid refund for an unrelated faulty service;`,
        `return of legitimate unused Cash-Funded Balance where legally required; or`,
        `correction of an unauthorised or incorrectly processed payment.`,
      ],
    ],
  },
  {
    title: '37. Reporting to Authorities or Providers',
    blocks: [
      `Where permitted or required by law, we may report or disclose relevant information to:`,
      [
        `law-enforcement authorities;`,
        `courts;`,
        `regulators;`,
        `sanctions authorities;`,
        `payment providers;`,
        `card issuers;`,
        `eSIM providers;`,
        `mobile network operators;`,
        `cybersecurity organisations; or`,
        `professional advisers.`,
      ],
      `We will not report a user merely because they submitted a genuine complaint, refund request or payment dispute.`,
    ],
  },
  {
    title: '38. Preservation of Records',
    blocks: [
      `Where reasonably necessary for:`,
      [
        `fraud investigation;`,
        `security;`,
        `a legal claim;`,
        `a Chargeback;`,
        `a regulatory request;`,
        `sanctions compliance; or`,
        `law-enforcement cooperation,`,
      ],
      `we may preserve relevant Account, payment, Order, network and communication records for an appropriate period.`,
      `Retention will be handled in accordance with the Privacy Policy and applicable law.`,
    ],
  },
  {
    title: '39. No Guarantee of Continuous Monitoring',
    blocks: [
      `ArvoSim may use manual and automated measures to identify suspicious activity, but we do not guarantee that every breach will be detected or prevented.`,
      `The existence of security or fraud controls does not transfer responsibility for a user's unlawful conduct to ArvoSim.`,
    ],
  },
  {
    title: '40. Complaints and Appeals',
    blocks: [
      `If you believe that your Account, eSIM, Order or Balance was restricted incorrectly, you may request a review by emailing: info@arvosim.com`,
      `Your request should include:`,
      [
        `the Account email address;`,
        `the affected Order or transaction;`,
        `the date of the restriction;`,
        `an explanation of why you believe the decision was incorrect;`,
        `relevant supporting information; and`,
        `the outcome you are seeking.`,
      ],
      `Where appropriate, the decision will be reviewed by a person who was not solely responsible for the original decision.`,
      `Submitting an appeal does not automatically suspend a restriction where continued access would create a security, legal, payment or network risk.`,
    ],
  },
  {
    title: '41. Changes to this Policy',
    blocks: [
      `We may update this Policy to reflect changes to:`,
      [
        `the Service;`,
        `available eSIM Plans;`,
        `payment and Balance functionality;`,
        `network-provider requirements;`,
        `security risks;`,
        `fraud patterns;`,
        `sanctions;`,
        `applicable law; or`,
        `our business operations.`,
      ],
      `The updated Policy will be published on arvosim.com with a revised "Last updated" date.`,
      `A material change will not retrospectively make previously permitted conduct a breach.`,
    ],
  },
  {
    title: '42. Governing Law',
    blocks: [
      `This Policy is governed by the laws of England and Wales.`,
      `The jurisdiction provisions in the ArvoSim Terms and Conditions apply to disputes arising from this Policy.`,
      `Mandatory consumer rights available in the user's country of residence remain unaffected.`,
    ],
  },
  {
    title: '43. Contact Information',
    blocks: [
      `Questions, reports and appeals concerning this Policy may be directed to ELVORIN LTD, company number 17344051, Suite 709, Avicenna House, 258–262 Romford Road, London, E7 9HZ, United Kingdom.`,
      `Email: info@arvosim.com. Website: arvosim.com.`,
    ],
  },
];

export default function AcceptableUsePage() {
  return (
    <PolicyPage
      title="Acceptable Use Policy"
      lastUpdated="31 July 2026"
      intro="This Acceptable Use Policy sets out the rules that apply when you access or use the ArvoSim Website, Account, Balance, eSIM Plans, mobile data connectivity and support. It protects users, prevents fraud and abuse, and ensures the Service is used only for its intended purpose."
      sections={sections}
    />
  );
}
