import { PolicyPage, type PolicySection } from '@/components/sections/PolicyPage';

const sections: PolicySection[] = [
  {
    title: '1. About this Policy',
    blocks: [
      `This eSIM Delivery and Activation Policy explains how eSIM orders placed through ArvoSim are processed, delivered, installed and activated.`,
      `It also explains what you should do if:`,
      [
        `you do not receive your eSIM;`,
        `the QR code does not work;`,
        `the eSIM cannot be installed;`,
        `the eSIM does not connect to a supported network; or`,
        `we are unable to fulfil your order.`,
      ],
      `This Policy forms part of the ArvoSim Terms and Conditions and should be read together with our:`,
      [
        `Terms and Conditions;`,
        `Refund and Cancellation Policy;`,
        `Payment and Wallet Policy; and`,
        `Privacy Policy.`,
      ],
      `ArvoSim is operated by ARVO LINE LTD, company number 17221404, Dept 6800, 196 High Road, Wood Green, London, United Kingdom, N22 8HH. Email: info@arvosim.com. Website: arvosim.com.`,
      `In this Policy, "ArvoSim", "we", "us" and "our" refer to ARVO LINE LTD.`,
    ],
  },
  {
    title: '2. Nature of the Product',
    blocks: [
      `An eSIM is a digital SIM profile supplied electronically. No physical SIM card or other physical item will be delivered.`,
      `Unless expressly stated otherwise in the relevant plan description, an ArvoSim eSIM provides mobile data only and does not include:`,
      [
        `a conventional mobile telephone number;`,
        `ordinary voice calls;`,
        `ordinary SMS services; or`,
        `emergency calling functionality.`,
      ],
      `Internet-based calling and messaging applications may operate using the available mobile data, but such applications are supplied and controlled by third parties.`,
    ],
  },
  {
    title: '3. How eSIM Orders Are Paid For',
    blocks: [
      `ArvoSim operates a Wallet-only purchasing model.`,
      `To order an eSIM, you must:`,
      [
        `create or access your ArvoSim Account;`,
        `add funds to your Wallet Balance using an accepted payment method;`,
        `select the required eSIM Plan;`,
        `confirm that your device is compatible;`,
        `confirm the destination, coverage, data allowance, validity period and price;`,
        `ensure that your Wallet Balance is sufficient; and`,
        `submit the Order.`,
      ],
      `An eSIM cannot be purchased directly using a payment card at checkout.`,
      `The price of the selected eSIM Plan will be deducted or reserved from your Wallet Balance when the Order is submitted.`,
    ],
  },
  {
    title: '4. Manual Order Processing',
    blocks: [
      `ArvoSim Orders are processed manually.`,
      `After an Order is submitted, a member of our team may need to:`,
      [
        `verify the Order information;`,
        `confirm that sufficient Wallet Balance is available;`,
        `check the availability of the selected Plan;`,
        `prepare or obtain the relevant eSIM profile;`,
        `perform payment, fraud or Account checks;`,
        `confirm the correct destination and Plan details; and`,
        `prepare the delivery email and installation information.`,
      ],
      `Submitting an Order does not mean that it has been automatically accepted or fulfilled.`,
      `An Order is accepted when we send the eSIM QR code or otherwise confirm that the eSIM has been issued and delivered.`,
    ],
  },
  {
    title: '5. Delivery Method',
    blocks: [
      `The eSIM QR code and any available installation information will be delivered to the email address associated with your ArvoSim Account.`,
      `ArvoSim does not currently deliver QR codes:`,
      [
        `by post;`,
        `by SMS;`,
        `through physical collection;`,
        `through a self-service Account download unless expressly stated otherwise; or`,
        `to an alternative email address that has not been verified.`,
      ],
      `You are responsible for ensuring that the email address associated with your Account is:`,
      [
        `correct;`,
        `complete;`,
        `active;`,
        `accessible by you; and`,
        `able to receive emails from ArvoSim.`,
      ],
      `We may ask you to verify your Account or email address before sending or resending an eSIM.`,
    ],
  },
  {
    title: '6. Estimated Delivery Time',
    blocks: [
      `The eSIM QR code will normally be sent within several hours after a valid Order has been successfully submitted.`,
      `This is an indicative processing period and not a guaranteed delivery deadline.`,
      `Delivery may take longer where:`,
      [
        `the Order is submitted outside our usual processing periods;`,
        `the Order is placed during a weekend or public holiday;`,
        `we are experiencing an unusually high volume of Orders;`,
        `additional Account, payment or security verification is required;`,
        `the selected Plan is temporarily unavailable;`,
        `confirmation is required from a network or technical provider;`,
        `there is an error or inconsistency in the Order details;`,
        `the Website, email service or another technical system is unavailable;`,
        `circumstances outside our reasonable control affect fulfilment; or`,
        `applicable law requires us to delay, review or refuse the transaction.`,
      ],
      `Where reasonably possible, we will notify you if we become aware of a material delay affecting your Order.`,
      `Because Orders are manually processed, you should place your Order sufficiently in advance of your intended travel or required activation time.`,
      `ArvoSim is not responsible for avoidable loss caused by submitting an Order immediately before departure or immediately before connectivity is required, unless the delay results from our breach of applicable law or failure to use reasonable care and skill.`,
    ],
  },
  {
    title: '7. When Delivery Is Complete',
    blocks: [
      `Delivery is normally considered complete when the email containing the eSIM QR code or equivalent activation information has been successfully dispatched to the email address associated with your Account.`,
      `Where we receive an automated delivery failure or bounce notification, we will not treat delivery as successfully completed until the issue has been reasonably addressed.`,
      `An email may still be filtered, delayed or placed in a spam, junk, promotions or similar folder by your email provider.`,
      `If the delivery email is not visible in your main inbox, you should:`,
      [
        `check your spam, junk and promotions folders;`,
        `search your mailbox for "ArvoSim";`,
        `confirm that your Account email address is correct;`,
        `allow a reasonable period for email delivery; and`,
        `contact info@arvosim.com if the email has still not arrived.`,
      ],
    ],
  },
  {
    title: '8. Incorrect or Inaccessible Email Address',
    blocks: [
      `You are responsible for providing and maintaining a correct and accessible email address.`,
      `If the QR code is sent to an incorrect address because you entered incorrect information, you should contact us promptly.`,
      `Before changing the delivery address or resending the eSIM, we may require:`,
      [
        `verification of your identity;`,
        `confirmation of Account ownership;`,
        `the relevant Order reference;`,
        `information about the Wallet top-up; or`,
        `other reasonable security information.`,
      ],
      `We will not knowingly send an eSIM QR code to an unverified third party.`,
      `A delay caused solely by incorrect, incomplete or inaccessible contact information supplied by the user will not normally be treated as a failure by ArvoSim to deliver the Order.`,
    ],
  },
  {
    title: '9. Order Availability',
    blocks: [
      `All eSIM Plans are subject to availability.`,
      `A Plan may become unavailable after an Order is submitted because of:`,
      [
        `changes made by a network or connectivity provider;`,
        `temporary capacity restrictions;`,
        `technical provisioning failures;`,
        `changes to destination coverage;`,
        `legal or regulatory restrictions;`,
        `sanctions or prohibited-jurisdiction requirements; or`,
        `errors in Website availability information.`,
      ],
      `If the selected Plan cannot be supplied, we may offer:`,
      [
        `a materially equivalent replacement Plan;`,
        `an alternative Plan for the same destination;`,
        `restoration of the full Plan price to your Wallet Balance; or`,
        `another remedy required by applicable law.`,
      ],
      `We will not substitute a materially different Plan without informing you and obtaining your agreement.`,
    ],
  },
  {
    title: '10. Preparing for Installation',
    blocks: [
      `Before installing the eSIM, you should confirm that:`,
      [
        `your device supports eSIM technology;`,
        `the device is not locked to another mobile operator;`,
        `the device supports the required network bands;`,
        `the device permits installation of another eSIM profile;`,
        `the operating system is up to date;`,
        `you have a stable Wi-Fi or internet connection;`,
        `you have access to the QR-code email on another screen or can use an alternative installation method; and`,
        `you have reviewed the installation and activation instructions.`,
      ],
      `Device compatibility may differ between countries, device variants and mobile operators, even where the same model name is used.`,
      `The presence of an "Add eSIM", "Add Mobile Plan" or similar option in the device settings may help indicate compatibility but does not guarantee that every Plan or network will be supported.`,
      `You are responsible for checking compatibility before submitting an Order.`,
    ],
  },
  {
    title: '11. Installing the eSIM',
    blocks: [
      `The delivery email will normally contain a QR code and may also include manual installation information.`,
      `To install the eSIM, you must follow the instructions applicable to your device.`,
      `Installation usually requires you to:`,
      [
        `connect the device to Wi-Fi or another reliable internet connection;`,
        `open the device's mobile network or SIM settings;`,
        `select the option to add an eSIM or mobile plan;`,
        `scan the supplied QR code or enter the manual activation information;`,
        `allow the device to download the eSIM profile;`,
        `label the eSIM so that it can be identified later; and`,
        `complete any device-specific configuration steps.`,
      ],
      `The exact wording and sequence will depend on the device manufacturer and operating system.`,
      `You should not interrupt the installation, restart the device unnecessarily or remove the eSIM while installation is in progress.`,
    ],
  },
  {
    title: '12. QR-Code Security and Single Use',
    blocks: [
      `An eSIM QR code is confidential activation information and may be restricted to a single installation.`,
      `You must not:`,
      [
        `publish the QR code;`,
        `post it on social media;`,
        `share it with an unauthorised person;`,
        `sell or transfer it;`,
        `scan it on a device you do not intend to use;`,
        `attempt to install it on several devices; or`,
        `allow another person to access the delivery email without authorisation.`,
      ],
      `If another person installs or uses the eSIM because you disclosed the QR code or failed to protect your email Account, we may be unable to issue a free replacement.`,
      `You must notify us promptly if you believe that the QR code or your Account has been compromised.`,
    ],
  },
  {
    title: '13. Installation Before Travel',
    blocks: [
      `Where the Plan's activation rules allow it, you may install the eSIM before travelling so that you can complete the installation while connected to a reliable Wi-Fi network.`,
      `However, before installing the eSIM, you must review the activation information for the selected Plan.`,
      `Unless the relevant Plan description states otherwise, the validity period begins when the eSIM first connects to a Supported Network in the applicable coverage area.`,
      `Some eSIM profiles may use different activation rules. Where a specific Plan activates:`,
      [
        `immediately after installation;`,
        `on a fixed date;`,
        `after a specified event; or`,
        `through another technical trigger,`,
      ],
      `the specific activation information supplied with that Plan will apply.`,
      `You should not activate mobile data or data roaming for the eSIM before you are ready to use the Plan unless the installation instructions require it.`,
    ],
  },
  {
    title: '14. Activation',
    blocks: [
      `An eSIM is activated when the relevant technical activation condition is met.`,
      `For most ArvoSim Plans, this occurs when the installed eSIM first connects to a Supported Network within the applicable coverage area.`,
      `Activation may require you to:`,
      [
        `select the ArvoSim eSIM as the mobile-data line;`,
        `enable the eSIM line;`,
        `enable data roaming for the eSIM;`,
        `disable automatic mobile-data switching;`,
        `select an available Supported Network;`,
        `enter the correct APN settings; or`,
        `restart the device.`,
      ],
      `Once activated, the Plan validity period normally runs continuously.`,
      `The Plan cannot ordinarily be:`,
      [
        `paused;`,
        `restarted;`,
        `transferred to another device;`,
        `extended because the user did not use it;`,
        `extended because the user left the coverage area; or`,
        `reset after the eSIM has been deleted.`,
      ],
    ],
  },
  {
    title: '15. Plan Validity',
    blocks: [
      `The validity period, data allowance, destination coverage and other material conditions will be shown in the Plan description or delivery information.`,
      `Unless expressly stated otherwise:`,
      [
        `the validity period begins upon first connection to a Supported Network;`,
        `the validity period runs continuously once started;`,
        `unused days cannot be postponed;`,
        `unused data does not roll over;`,
        `unused data expires at the end of the validity period; and`,
        `a separate Plan must be purchased if additional data is required.`,
      ],
      `The user is responsible for purchasing a Plan suitable for the intended travel period.`,
    ],
  },
  {
    title: '16. Network Connection',
    blocks: [
      `After activation, the eSIM will attempt to connect to an available Supported Network.`,
      `Connectivity may depend on:`,
      [
        `local network availability;`,
        `the user's location;`,
        `device compatibility;`,
        `supported network frequencies;`,
        `network congestion;`,
        `local infrastructure;`,
        `buildings and physical obstructions;`,
        `data-roaming settings;`,
        `APN configuration;`,
        `network maintenance;`,
        `local laws or restrictions; and`,
        `temporary operator outages.`,
      ],
      `ArvoSim does not guarantee that every Supported Network will be available at every location or at all times.`,
      `A Plan advertised as supporting 5G may connect through 4G or LTE where 5G is unavailable, restricted or unsupported by the device.`,
    ],
  },
  {
    title: '17. Data Roaming',
    blocks: [
      `Many travel eSIM Plans require data roaming to be enabled for the eSIM line.`,
      `Before enabling data roaming, you should confirm that:`,
      [
        `the ArvoSim eSIM is selected for mobile data;`,
        `your primary SIM is not being used for mobile data;`,
        `automatic mobile-data switching is disabled where appropriate; and`,
        `roaming is enabled only for the intended eSIM line.`,
      ],
      `ArvoSim is not responsible for charges imposed by your primary mobile provider because the wrong SIM was selected, automatic switching remained enabled or the device was configured incorrectly.`,
    ],
  },
  {
    title: '18. If the QR Code Does Not Work',
    blocks: [
      `A QR code may fail because:`,
      [
        `it has already been installed;`,
        `it has been scanned on another device;`,
        `the device does not support eSIM;`,
        `the device is carrier-locked;`,
        `the device has reached its eSIM-profile limit;`,
        `there is no stable internet connection;`,
        `the device software is outdated;`,
        `the code has been entered incorrectly;`,
        `the eSIM was previously deleted; or`,
        `there is a technical provisioning error.`,
      ],
      `If the QR code does not work, you should:`,
      [
        `stop repeated installation attempts;`,
        `take a screenshot of the error message;`,
        `confirm the device model and operating-system version;`,
        `confirm whether the device is network-unlocked;`,
        `retain the original delivery email;`,
        `avoid deleting any partially installed eSIM profile; and`,
        `contact info@arvosim.com.`,
      ],
      `We may ask you to provide screenshots, settings information or other reasonable diagnostic details.`,
      `You should not delete the eSIM unless our support team or the relevant installation instructions advise you to do so.`,
    ],
  },
  {
    title: '19. If the eSIM Installs but Does Not Connect',
    blocks: [
      `If the eSIM is installed but does not connect, you should check that:`,
      [
        `you are within the Plan's coverage area;`,
        `the eSIM line is enabled;`,
        `the eSIM is selected for mobile data;`,
        `data roaming is enabled where required;`,
        `the primary SIM is not overriding the data connection;`,
        `the correct APN is entered;`,
        `automatic network selection has been attempted;`,
        `an available Supported Network has been selected;`,
        `airplane mode has been switched on and off; and`,
        `the device has been restarted.`,
      ],
      `You should contact us if the issue continues.`,
      `We may require reasonable cooperation with troubleshooting before determining that the eSIM is faulty or unavailable.`,
      `The requirement to cooperate does not affect any mandatory consumer rights.`,
    ],
  },
  {
    title: '20. Replacement eSIM',
    blocks: [
      `Where an eSIM is invalid, incorrectly provisioned or otherwise faulty for reasons attributable to ArvoSim or its providers, we may issue:`,
      [
        `corrected installation information;`,
        `a replacement QR code;`,
        `a replacement eSIM;`,
        `an equivalent Plan; or`,
        `another appropriate remedy.`,
      ],
      `A free replacement will not normally be available where:`,
      [
        `the QR code was shared with another person;`,
        `the eSIM was installed on the wrong device;`,
        `the eSIM was deleted after successful installation;`,
        `the user changed devices after installation;`,
        `the device is incompatible or carrier-locked;`,
        `incorrect settings caused the problem;`,
        `the user failed to follow reasonable instructions; or`,
        `the eSIM has already been used.`,
      ],
      `Each case will be assessed according to its circumstances and applicable consumer law.`,
    ],
  },
  {
    title: '21. Delayed or Failed Delivery',
    blocks: [
      `If an eSIM has not been delivered within a reasonable period, you should contact info@arvosim.com.`,
      `We will investigate whether:`,
      [
        `the Order was successfully submitted;`,
        `the Plan price was deducted;`,
        `the delivery email was dispatched;`,
        `the email address was correct;`,
        `the email was rejected or returned;`,
        `the Plan remained available; and`,
        `a technical or manual-processing error occurred.`,
      ],
      `Depending on the circumstances, we may:`,
      [
        `complete the Order;`,
        `resend the delivery email;`,
        `send the QR code to a verified replacement email address;`,
        `issue a replacement eSIM;`,
        `offer an equivalent Plan;`,
        `restore the full Plan price to the Wallet Balance; or`,
        `provide another remedy required by applicable law.`,
      ],
    ],
  },
  {
    title: '22. Failure to Deliver Before Travel',
    blocks: [
      `You should order the eSIM sufficiently in advance of your planned travel.`,
      `If we fail to deliver the eSIM within the stated indicative period and the delay materially affects the purpose of the Order, you should contact us as soon as possible.`,
      `Where the eSIM has not been delivered or used, you may request cancellation and restoration of the full Plan price to your Wallet Balance.`,
      `If we expressly agreed to deliver by a specific deadline and fail to meet that deadline, any remedies available under applicable law will remain unaffected.`,
      `We do not reimburse replacement connectivity, roaming, accommodation, missed transport or other consequential expenses unless such liability cannot legally be excluded or the expense was expressly approved by us in advance.`,
    ],
  },
  {
    title: '23. Cancellation Before Delivery',
    blocks: [
      `You may request cancellation before the QR code or activation information has been delivered.`,
      `Cancellation requests must be sent to info@arvosim.com and should include:`,
      [
        `the Account email address;`,
        `the Order reference;`,
        `the destination;`,
        `the selected Plan; and`,
        `the reason for the request.`,
      ],
      `Because Orders are manually processed, we cannot guarantee that a cancellation message will be reviewed before delivery if fulfilment is already underway.`,
      `If the Order has not yet been accepted or fulfilled, the full Plan price will be restored to the Wallet Balance.`,
    ],
  },
  {
    title: '24. Faulty or Unavailable Digital Content',
    blocks: [
      `If an eSIM is:`,
      [
        `not delivered;`,
        `invalid;`,
        `technically unusable;`,
        `materially different from its description;`,
        `incapable of being provisioned; or`,
        `unable to connect because of a fault attributable to the supplied eSIM,`,
      ],
      `we may first attempt to correct the issue by resending, repairing, reprovisioning or replacing the eSIM.`,
      `Such action will be taken within a reasonable time and without significant inconvenience, taking into account the nature of travel connectivity and the date on which the eSIM is required.`,
      `If correction or replacement is impossible, disproportionate or not completed within a reasonable time, we may provide:`,
      [
        `restoration of the full or appropriate portion of the Plan price to the Wallet Balance;`,
        `a full or proportionate refund where required;`,
        `an equivalent replacement Plan; or`,
        `another remedy required by applicable law.`,
      ],
      `Nothing in this Policy excludes or restricts mandatory rights relating to faulty or misdescribed digital content.`,
    ],
  },
  {
    title: '25. Used eSIMs',
    blocks: [
      `For refund and support purposes, an eSIM will generally be treated as used when network or provider records show that it has:`,
      [
        `connected to a Supported Network; and`,
        `consumed any amount of mobile data.`,
      ],
      `Installation alone will not necessarily mean that the data Plan has been used if the eSIM has not connected or consumed data.`,
      `However, deleting, transferring, sharing or compromising an installed eSIM may affect our ability to replace or reissue it.`,
      `Network or provider records will normally be used to determine activation and usage, unless there is clear evidence of an error.`,
    ],
  },
  {
    title: '26. Digital Delivery Consent',
    blocks: [
      `An eSIM is digital content supplied without a tangible medium.`,
      `Before the eSIM is delivered during any applicable statutory cancellation period, we may require you to:`,
      [
        `expressly request or consent to the supply of the eSIM before the cancellation period has ended; and`,
        `acknowledge that the statutory cancellation right may be lost once digital supply begins.`,
      ],
      `Supply begins when the QR code or equivalent activation information is delivered to the email address associated with the Account.`,
      `Where required, this consent and acknowledgement must be collected separately during the ordering process and recorded in the Order confirmation.`,
      `The voluntary refund rights offered by ArvoSim and mandatory rights relating to faulty digital content remain subject to the Terms and Conditions and Refund and Cancellation Policy.`,
    ],
  },
  {
    title: '27. Circumstances Outside Our Control',
    blocks: [
      `Delivery or activation may be affected by events outside our reasonable control, including:`,
      [
        `network outages;`,
        `email-delivery failures;`,
        `internet disruption;`,
        `power failures;`,
        `cyber incidents;`,
        `third-party provider failures;`,
        `government restrictions;`,
        `sanctions;`,
        `telecommunications restrictions;`,
        `natural disasters;`,
        `severe weather;`,
        `war or civil disturbance;`,
        `public-health emergencies; or`,
        `failure of communications infrastructure.`,
      ],
      `We will take reasonable steps to minimise the effect of such events and fulfil or remedy affected Orders where practicable.`,
    ],
  },
  {
    title: '28. Support Information',
    blocks: [
      `For delivery, installation or activation support, contact: Email: info@arvosim.com`,
      `To help us investigate promptly, include:`,
      [
        `your Account email address;`,
        `your Order reference;`,
        `the destination and Plan;`,
        `your device manufacturer and model;`,
        `your operating-system version;`,
        `the date and approximate time of installation;`,
        `a screenshot of any error message; and`,
        `a description of the troubleshooting steps already attempted.`,
      ],
      `Do not include full payment-card details, passwords or other unnecessary sensitive information in your support request.`,
    ],
  },
  {
    title: '29. Changes to this Policy',
    blocks: [
      `We may update this Policy to reflect changes to:`,
      [
        `Order processing;`,
        `delivery methods;`,
        `eSIM technology;`,
        `network-provider requirements;`,
        `the Website;`,
        `applicable law; or`,
        `our business operations.`,
      ],
      `The updated version will be published on arvosim.com with a revised "Last updated" date.`,
      `A change will not retrospectively reduce rights relating to an Order already accepted.`,
    ],
  },
  {
    title: '30. Contact Details',
    blocks: [
      `Questions about this Policy may be directed to ARVO LINE LTD, company number 17221404, Dept 6800, 196 High Road, Wood Green, London, United Kingdom, N22 8HH.`,
      `Email: info@arvosim.com. Website: arvosim.com.`,
    ],
  },
];

export default function EsimDeliveryPage() {
  return (
    <PolicyPage
      title="eSIM Delivery and Activation Policy"
      lastUpdated="31 July 2026"
      intro="This eSIM Delivery and Activation Policy explains how eSIM orders placed through ArvoSim are processed, delivered, installed and activated, and what you should do if you do not receive your eSIM, the QR code does not work, or the eSIM cannot be installed or connected."
      sections={sections}
    />
  );
}
